/* ============================================================
   ranked-texts.js — 世界ランキング（ランク戦）の文言・9言語
   ------------------------------------------------------------
   アプリ側のランク戦の画面（これから作る ranked.js）が使う。
   作りは sushi-arm.js / pll-share.js と同じで、I18N に無いキーだけ足す
   （既存のキーは上書きしない）。ja だけは必ずある。

   参加時の説明（rkJoinBody）は3行だけ（2026-10-04 に短くした）:
     ・登録されるのはニックネームとランク戦の記録
     ・それ以外のデータは送らない
     ・いつでもやめられ、やめると記録はすべて消える
     サーバーの仕組み（出題・手順の再生など）はここには書かない方針
   ============================================================ */
(function (global) {
  'use strict';

  const RANKED_I18N = {
    ja: {
      rkTitle: '世界ランキング',
      rkJoinTitle: '世界ランキングに参加する',
      rkJoinBody:
        'ニックネームとランク戦の記録が、世界ランキングに登録されます。\n' +
        'それ以外のデータが送られることはありません。\n' +
        '参加はいつでもやめられ、やめると記録はすべて消えます。',
      rkRules: 'ランク戦のルール：インスペクションは15秒まで／💡ヘルプ・OLL・PLL・ZBLLは使えません／一時停止はできません',
      rkNickLabel: 'ニックネーム（7文字まで・ランキングに表示されます）',
      rkNickBad: "使用できない文字または不適切な表現が含まれています",
      rkNickLength: "ニックネームは1〜7文字で入力してください",      rkJoin: '参加する',
      rkNotNow: 'やめておく',
      rkStart: 'ランク戦をはじめる',
      rkInspection: 'インスペクション',
      rkSending: '記録を送っています…',
      rkResultOk: '記録しました',
      rkRank: '{n}位',
      rkNewBest: '自己ベスト更新！',
      rkErrNotSolved: '揃っていない状態で届いたため、記録できませんでした',
      rkErrInspection: 'インスペクションが15秒を超えたため、記録できませんでした',
      rkErrTime: 'タイムを確かめられなかったため、記録できませんでした',
      rkErrExpired: '時間が経ちすぎたため、この出題は終わりました',
      rkErrOffline: 'サーバーにつながりません。電波のある場所でもう一度お試しください',
      rkErrTooSoon: '少し待ってから、もう一度お試しください',
      rkLeave: 'ランキングへの参加をやめる',
      rkLeaveConfirm: "本当にランキングから削除しますか？送った記録はすべて消え、元に戻せません。",
      rkRename: 'ニックネームを変える',
      rkEmpty: 'まだ記録がありません',
      rkFirstMoveHint: '1手目でスタート',
      rkAssistUsed: 'ガイドを使ったため、今回は記録されません（練習として続けられます）',
      rkPaused: '一時停止したため、今回は記録されません（練習として続けられます）',
      rkCancelled: 'ランク戦を中止しました',
      rkViewRanking: 'ランキングを見る',
      rkSave: '保存する',
      rkCancelBtn: 'キャンセル',
      rkMyBest: '自己ベスト',
      rkNoRecordYet: 'まだ記録がありません',
      rkPlayers: '{n}人',
      rkMoves: '{n}手',
      rkLeaveOk: "削除する",
      rkRulesTitle: "ランク戦のルール",
      rkRuleInspL: "インスペクション",
      rkRuleInspV: "15秒まで",
      rkRuleGuideL: "💡ヘルプ / OLL / PLL / ZBLL",
      rkRuleGuideV: "使用不可",
      rkRulePauseL: "一時停止",
      rkRulePauseV: "不可",
      rkFxFirst: "1位",
      rkFxTop: "{n}位",
      rkFxPb: "自己ベスト更新",
      rkFxTap: "タップで閉じる",
      rkYou: "あなた",
      rkReplayOpen: "{n}位の解き方を見る",
      rkReplayScramble: "スクランブル",
      rkReplayStartPos: "スクランブル直後",
      rkReplayDrag: "なぞると縦・横に90°ずつ回ります",
      rkReplayTitle: "解き方",
      rkModeRandomSize: "ランダムサイズモード",
      rkModeRandomSizeDesc: "1手回すたびに、キューブの大きさが1%〜160%のどれかにランダムで変わります",
      rkModeNormal: "通常モード",
      rkModeNormalDesc: "いつものキューブで、速さを競います",
      rkSeasonNow: "今月",
      rkSeasonEnded: "終了",
      rkSeasonEndedNote: "この月は終わりました。今月のランキングで挑戦しよう"
    },
    en: {
      rkTitle: 'World Ranking',
      rkJoinTitle: 'Join the World Ranking',
      rkJoinBody:
        'Your nickname and ranked-solve records will be added to the World Ranking.\n' +
        'No other data is ever sent.\n' +
        'You can leave at any time, and leaving deletes all your records.',
      rkRules: 'Ranked rules: 15 s inspection / no 💡 Help, OLL, PLL or ZBLL / no pausing',
      rkNickLabel: 'Nickname (up to 7 characters, shown on the ranking)',
      rkNickBad: "Your nickname contains characters or words that can’t be used",
      rkNickLength: "Please enter a nickname of 1–7 characters",      rkJoin: 'Join',
      rkNotNow: 'Not now',
      rkStart: 'Start a ranked solve',
      rkInspection: 'Inspection',
      rkSending: 'Sending your record…',
      rkResultOk: 'Recorded',
      rkRank: '#{n}',
      rkNewBest: 'New personal best!',
      rkErrNotSolved: "The cube wasn't solved when it arrived, so this wasn't recorded",
      rkErrInspection: 'Inspection went over 15 seconds, so this wasn’t recorded',
      rkErrTime: "The time couldn't be verified, so this wasn't recorded",
      rkErrExpired: 'Too much time has passed — this scramble has ended',
      rkErrOffline: "Can't reach the server. Please try again where you have a signal",
      rkErrTooSoon: 'Please wait a moment and try again',
      rkLeave: 'Leave the ranking',
      rkLeaveConfirm: "Really remove yourself from the ranking? Every record you sent will be deleted and cannot be restored.",
      rkRename: 'Change nickname',
      rkEmpty: 'No records yet',
      rkFirstMoveHint: 'Timer starts on your first move',
      rkAssistUsed: "A guide was used, so this won't be recorded (you can keep practicing)",
      rkPaused: "The timer was paused, so this won't be recorded (you can keep practicing)",
      rkCancelled: 'Ranked solve cancelled',
      rkViewRanking: 'View ranking',
      rkSave: 'Save',
      rkCancelBtn: 'Cancel',
      rkMyBest: 'Personal best',
      rkNoRecordYet: 'No record yet',
      rkPlayers: 'Players: {n}',
      rkMoves: '{n} mv',
      rkLeaveOk: "Remove",
      rkRulesTitle: "Ranked rules",
      rkRuleInspL: "Inspection",
      rkRuleInspV: "Up to 15 s",
      rkRuleGuideL: "💡 Help / OLL / PLL / ZBLL",
      rkRuleGuideV: "Not allowed",
      rkRulePauseL: "Pausing",
      rkRulePauseV: "Not allowed",
      rkFxFirst: "WORLD No.1",
      rkFxTop: "WORLD No.{n}",
      rkFxPb: "NEW PERSONAL BEST",
      rkFxTap: "Tap to continue",
      rkYou: "You",
      rkReplayOpen: "See how #{n} solved it",
      rkReplayScramble: "Scramble",
      rkReplayStartPos: "Scrambled",
      rkReplayDrag: "Swipe to turn the cube 90° at a time",
      rkReplayTitle: "Solve replay",
      rkModeRandomSize: "Random Size Mode",
      rkModeRandomSizeDesc: "Every turn changes the cube to a random size between 1% and 160%",
      rkModeNormal: "Normal Mode",
      rkModeNormalDesc: "A regular cube — just be fast",
      rkSeasonNow: "This month",
      rkSeasonEnded: "Ended",
      rkSeasonEndedNote: "This month has ended. Take on this month's ranking!"
    },
    'zh-CN': {
      rkTitle: '世界排行榜',
      rkJoinTitle: '加入世界排行榜',
      rkJoinBody:
        '你的昵称和排位赛记录会登记到世界排行榜。\n' +
        '不会发送任何其他数据。\n' +
        '可以随时退出，退出后记录会全部删除。',
      rkRules: '排位赛规则：观察最多15秒／不能使用💡提示、OLL、PLL、ZBLL／不能暂停',
      rkNickLabel: '昵称（最多7个字，会显示在排行榜上）',
      rkNickBad: "昵称包含无法使用的字符或不当的表达",
      rkNickLength: "请输入1〜7个字的昵称",      rkJoin: '加入',
      rkNotNow: '暂不加入',
      rkStart: '开始排位赛',
      rkInspection: '观察',
      rkSending: '正在发送记录…',
      rkResultOk: '已记录',
      rkRank: '第{n}名',
      rkNewBest: '刷新个人最佳！',
      rkErrNotSolved: '提交时魔方未复原，无法记录',
      rkErrInspection: '观察超过15秒，无法记录',
      rkErrTime: '无法核实时间，无法记录',
      rkErrExpired: '时间过长，本题已结束',
      rkErrOffline: '无法连接服务器，请在有信号的地方再试一次',
      rkErrTooSoon: '请稍等片刻再试',
      rkLeave: '退出排行榜',
      rkLeaveConfirm: "确定要从排行榜中删除吗？你提交的所有记录都会被删除，且无法恢复。",
      rkRename: '修改昵称',
      rkEmpty: '还没有记录',
      rkFirstMoveHint: '转动第一步开始计时',
      rkAssistUsed: '使用了提示，本次不计入记录（可以继续练习）',
      rkPaused: '暂停过计时，本次不计入记录（可以继续练习）',
      rkCancelled: '已取消排位赛',
      rkViewRanking: '查看排行榜',
      rkSave: '保存',
      rkCancelBtn: '取消',
      rkMyBest: '个人最佳',
      rkNoRecordYet: '还没有记录',
      rkPlayers: '{n}人',
      rkMoves: '{n}步',
      rkLeaveOk: "删除",
      rkRulesTitle: "排位赛规则",
      rkRuleInspL: "观察",
      rkRuleInspV: "最多15秒",
      rkRuleGuideL: "💡提示 / OLL / PLL / ZBLL",
      rkRuleGuideV: "不可使用",
      rkRulePauseL: "暂停",
      rkRulePauseV: "不可",
      rkFxFirst: "世界第1名",
      rkFxTop: "世界第{n}名",
      rkFxPb: "刷新个人最佳",
      rkFxTap: "点击继续",
      rkYou: "你",
      rkReplayOpen: "查看第{n}名的解法",
      rkReplayScramble: "打乱",
      rkReplayStartPos: "打乱后",
      rkReplayDrag: "滑动可上下左右各转90°",
      rkReplayTitle: "解法回放",
      rkModeRandomSize: "随机大小模式",
      rkModeRandomSizeDesc: "每转一步，魔方的大小都会随机变成1%～160%之间的某个值",
      rkModeNormal: "普通模式",
      rkModeNormalDesc: "用普通的魔方比速度",
      rkSeasonNow: "本月",
      rkSeasonEnded: "已结束",
      rkSeasonEndedNote: "这个月已经结束了，来挑战本月的排行榜吧"
    },
    'zh-TW': {
      rkTitle: '世界排行榜',
      rkJoinTitle: '加入世界排行榜',
      rkJoinBody:
        '你的暱稱和排位賽紀錄會登記到世界排行榜。\n' +
        '不會傳送任何其他資料。\n' +
        '可以隨時退出，退出後紀錄會全部刪除。',
      rkRules: '排位賽規則：觀察最多15秒／不能使用💡提示、OLL、PLL、ZBLL／不能暫停',
      rkNickLabel: '暱稱（最多7個字，會顯示在排行榜上）',
      rkNickBad: "暱稱包含無法使用的字元或不當的用語",
      rkNickLength: "請輸入1〜7個字的暱稱",      rkJoin: '加入',
      rkNotNow: '暫不加入',
      rkStart: '開始排位賽',
      rkInspection: '觀察',
      rkSending: '正在傳送紀錄…',
      rkResultOk: '已記錄',
      rkRank: '第{n}名',
      rkNewBest: '刷新個人最佳！',
      rkErrNotSolved: '提交時方塊未復原，無法記錄',
      rkErrInspection: '觀察超過15秒，無法記錄',
      rkErrTime: '無法核實時間，無法記錄',
      rkErrExpired: '時間過長，本題已結束',
      rkErrOffline: '無法連線到伺服器，請在有訊號的地方再試一次',
      rkErrTooSoon: '請稍等片刻再試',
      rkLeave: '退出排行榜',
      rkLeaveConfirm: "確定要從排行榜中刪除嗎？你提交的所有紀錄都會被刪除，且無法復原。",
      rkRename: '修改暱稱',
      rkEmpty: '還沒有紀錄',
      rkFirstMoveHint: '轉動第一步開始計時',
      rkAssistUsed: '使用了提示，本次不計入紀錄（可以繼續練習）',
      rkPaused: '暫停過計時，本次不計入紀錄（可以繼續練習）',
      rkCancelled: '已取消排位賽',
      rkViewRanking: '查看排行榜',
      rkSave: '儲存',
      rkCancelBtn: '取消',
      rkMyBest: '個人最佳',
      rkNoRecordYet: '還沒有紀錄',
      rkPlayers: '{n}人',
      rkMoves: '{n}步',
      rkLeaveOk: "刪除",
      rkRulesTitle: "排位賽規則",
      rkRuleInspL: "觀察",
      rkRuleInspV: "最多15秒",
      rkRuleGuideL: "💡提示 / OLL / PLL / ZBLL",
      rkRuleGuideV: "不可使用",
      rkRulePauseL: "暫停",
      rkRulePauseV: "不可",
      rkFxFirst: "世界第1名",
      rkFxTop: "世界第{n}名",
      rkFxPb: "刷新個人最佳",
      rkFxTap: "點擊繼續",
      rkYou: "你",
      rkReplayOpen: "查看第{n}名的解法",
      rkReplayScramble: "打亂",
      rkReplayStartPos: "打亂後",
      rkReplayDrag: "滑動可上下左右各轉90°",
      rkReplayTitle: "解法重播",
      rkModeRandomSize: "隨機大小模式",
      rkModeRandomSizeDesc: "每轉一步，方塊的大小都會隨機變成1%～160%之間的某個值",
      rkModeNormal: "普通模式",
      rkModeNormalDesc: "用一般的方塊比速度",
      rkSeasonNow: "本月",
      rkSeasonEnded: "已結束",
      rkSeasonEndedNote: "這個月已經結束了，來挑戰本月的排行榜吧"
    },
    ko: {
      rkTitle: '세계 랭킹',
      rkJoinTitle: '세계 랭킹에 참가하기',
      rkJoinBody:
        '닉네임과 랭크전 기록이 세계 랭킹에 등록됩니다.\n' +
        '그 밖의 데이터는 보내지 않습니다.\n' +
        '참가는 언제든지 그만둘 수 있으며, 그만두면 기록은 모두 삭제됩니다.',
      rkRules: '랭크전 규칙: 관찰은 15초까지 / 💡도움말·OLL·PLL·ZBLL 사용 불가 / 일시정지 불가',
      rkNickLabel: '닉네임(최대 7자, 랭킹에 표시됩니다)',
      rkNickBad: "사용할 수 없는 문자나 부적절한 표현이 포함되어 있습니다",
      rkNickLength: "닉네임은 1~7자로 입력해 주세요",      rkJoin: '참가하기',
      rkNotNow: '다음에',
      rkStart: '랭크전 시작',
      rkInspection: '관찰',
      rkSending: '기록을 보내는 중…',
      rkResultOk: '기록했습니다',
      rkRank: '{n}위',
      rkNewBest: '개인 최고 기록 갱신!',
      rkErrNotSolved: '맞춰지지 않은 상태로 도착해 기록하지 못했습니다',
      rkErrInspection: '관찰이 15초를 넘어 기록하지 못했습니다',
      rkErrTime: '시간을 확인할 수 없어 기록하지 못했습니다',
      rkErrExpired: '시간이 너무 지나 이 문제는 종료되었습니다',
      rkErrOffline: '서버에 연결할 수 없습니다. 신호가 잡히는 곳에서 다시 시도해 주세요',
      rkErrTooSoon: '잠시 후 다시 시도해 주세요',
      rkLeave: '랭킹 참가 그만두기',
      rkLeaveConfirm: "정말 랭킹에서 삭제할까요? 보낸 기록이 모두 지워지며 되돌릴 수 없습니다.",
      rkRename: '닉네임 변경',
      rkEmpty: '아직 기록이 없습니다',
      rkFirstMoveHint: '첫 수를 돌리면 시작',
      rkAssistUsed: '가이드를 사용해 이번 기록은 남지 않습니다(연습으로 계속할 수 있어요)',
      rkPaused: '일시정지해서 이번 기록은 남지 않습니다(연습으로 계속할 수 있어요)',
      rkCancelled: '랭크전을 중단했습니다',
      rkViewRanking: '랭킹 보기',
      rkSave: '저장',
      rkCancelBtn: '취소',
      rkMyBest: '개인 최고',
      rkNoRecordYet: '아직 기록이 없습니다',
      rkPlayers: '{n}명',
      rkMoves: '{n}수',
      rkLeaveOk: "삭제",
      rkRulesTitle: "랭크전 규칙",
      rkRuleInspL: "관찰",
      rkRuleInspV: "15초까지",
      rkRuleGuideL: "💡도움말 / OLL / PLL / ZBLL",
      rkRuleGuideV: "사용 불가",
      rkRulePauseL: "일시정지",
      rkRulePauseV: "불가",
      rkFxFirst: "세계 1위",
      rkFxTop: "세계 {n}위",
      rkFxPb: "자기 최고 기록 경신",
      rkFxTap: "탭하여 계속",
      rkYou: "나",
      rkReplayOpen: "{n}위의 풀이 보기",
      rkReplayScramble: "스크램블",
      rkReplayStartPos: "스크램블 직후",
      rkReplayDrag: "밀면 가로·세로로 90°씩 돌아가요",
      rkReplayTitle: "풀이 다시 보기",
      rkModeRandomSize: "랜덤 사이즈 모드",
      rkModeRandomSizeDesc: "한 번 돌릴 때마다 큐브 크기가 1%~160% 사이에서 무작위로 바뀝니다",
      rkModeNormal: "일반 모드",
      rkModeNormalDesc: "평소 큐브로 속도를 겨룹니다",
      rkSeasonNow: "이번 달",
      rkSeasonEnded: "종료",
      rkSeasonEndedNote: "이 달은 끝났어요. 이번 달 랭킹에 도전해 보세요"
    },
    es: {
      rkTitle: 'Ranking mundial',
      rkJoinTitle: 'Unirse al ranking mundial',
      rkJoinBody:
        'Tu apodo y tus récords clasificatorios se registrarán en el ranking mundial.\n' +
        'No se envía ningún otro dato.\n' +
        'Puedes salir cuando quieras; al salir se borran todos tus récords.',
      rkRules: 'Reglas: inspección de 15 s / sin 💡 Ayuda, OLL, PLL ni ZBLL / sin pausas',
      rkNickLabel: 'Apodo (hasta 7 caracteres; se muestra en el ranking)',
      rkNickBad: "El apodo contiene caracteres o expresiones no permitidos",
      rkNickLength: "Escribe un apodo de 1 a 7 caracteres",      rkJoin: 'Unirme',
      rkNotNow: 'Ahora no',
      rkStart: 'Empezar partida clasificatoria',
      rkInspection: 'Inspección',
      rkSending: 'Enviando tu récord…',
      rkResultOk: 'Registrado',
      rkRank: 'Puesto {n}',
      rkNewBest: '¡Nuevo récord personal!',
      rkErrNotSolved: 'El cubo no estaba resuelto al llegar, así que no se registró',
      rkErrInspection: 'La inspección superó los 15 segundos, así que no se registró',
      rkErrTime: 'No se pudo verificar el tiempo, así que no se registró',
      rkErrExpired: 'Ha pasado demasiado tiempo: esta mezcla ha terminado',
      rkErrOffline: 'No se puede conectar con el servidor. Inténtalo de nuevo donde tengas señal',
      rkErrTooSoon: 'Espera un momento y vuelve a intentarlo',
      rkLeave: 'Salir del ranking',
      rkLeaveConfirm: "¿Seguro que quieres borrarte del ranking? Se eliminarán todos tus récords y no se podrán recuperar.",
      rkRename: 'Cambiar apodo',
      rkEmpty: 'Todavía no hay récords',
      rkFirstMoveHint: 'El tiempo empieza con tu primer giro',
      rkAssistUsed: 'Usaste una guía, así que no se registrará (puedes seguir practicando)',
      rkPaused: 'Pausaste el cronómetro, así que no se registrará (puedes seguir practicando)',
      rkCancelled: 'Partida clasificatoria cancelada',
      rkViewRanking: 'Ver ranking',
      rkSave: 'Guardar',
      rkCancelBtn: 'Cancelar',
      rkMyBest: 'Mejor marca',
      rkNoRecordYet: 'Aún sin récord',
      rkPlayers: 'Jugadores: {n}',
      rkMoves: '{n} giros',
      rkLeaveOk: "Borrar",
      rkRulesTitle: "Reglas",
      rkRuleInspL: "Inspección",
      rkRuleInspV: "Hasta 15 s",
      rkRuleGuideL: "💡 Ayuda / OLL / PLL / ZBLL",
      rkRuleGuideV: "No permitido",
      rkRulePauseL: "Pausa",
      rkRulePauseV: "No permitida",
      rkFxFirst: "¡Nº 1 DEL MUNDO!",
      rkFxTop: "¡Nº {n} DEL MUNDO!",
      rkFxPb: "¡NUEVO RÉCORD PERSONAL!",
      rkFxTap: "Toca para continuar",
      rkYou: "Tú",
      rkReplayOpen: "Ver cómo resolvió el n.º {n}",
      rkReplayScramble: "Mezcla",
      rkReplayStartPos: "Recién mezclado",
      rkReplayDrag: "Desliza para girarlo 90° cada vez",
      rkReplayTitle: "Repetición",
      rkModeRandomSize: "Modo tamaño aleatorio",
      rkModeRandomSizeDesc: "Cada giro cambia el cubo a un tamaño aleatorio entre el 1 % y el 160 %",
      rkModeNormal: "Modo normal",
      rkModeNormalDesc: "Un cubo normal: solo sé rápido",
      rkSeasonNow: "Este mes",
      rkSeasonEnded: "Terminado",
      rkSeasonEndedNote: "Este mes ya terminó. ¡Prueba el ranking de este mes!"
    },
    id: {
      rkTitle: 'Peringkat Dunia',
      rkJoinTitle: 'Ikut Peringkat Dunia',
      rkJoinBody:
        'Nama panggilan dan catatan solve peringkatmu akan didaftarkan ke Peringkat Dunia.\n' +
        'Tidak ada data lain yang dikirim.\n' +
        'Kamu bisa berhenti kapan saja, dan semua catatanmu akan dihapus.',
      rkRules: 'Aturan: inspeksi 15 detik / tanpa 💡 Bantuan, OLL, PLL, ZBLL / tidak bisa dijeda',
      rkNickLabel: 'Nama panggilan (maks. 7 karakter, tampil di peringkat)',
      rkNickBad: "Nama panggilan berisi karakter atau kata yang tidak boleh dipakai",
      rkNickLength: "Masukkan nama panggilan 1–7 karakter",      rkJoin: 'Ikut',
      rkNotNow: 'Nanti saja',
      rkStart: 'Mulai solve peringkat',
      rkInspection: 'Inspeksi',
      rkSending: 'Mengirim catatan…',
      rkResultOk: 'Tercatat',
      rkRank: 'Peringkat {n}',
      rkNewBest: 'Rekor pribadi baru!',
      rkErrNotSolved: 'Kubus belum selesai saat dikirim, jadi tidak tercatat',
      rkErrInspection: 'Inspeksi lebih dari 15 detik, jadi tidak tercatat',
      rkErrTime: 'Waktu tidak bisa diverifikasi, jadi tidak tercatat',
      rkErrExpired: 'Sudah terlalu lama — acakan ini telah berakhir',
      rkErrOffline: 'Tidak bisa terhubung ke server. Coba lagi di tempat yang ada sinyal',
      rkErrTooSoon: 'Tunggu sebentar lalu coba lagi',
      rkLeave: 'Berhenti ikut peringkat',
      rkLeaveConfirm: "Yakin ingin menghapus diri dari peringkat? Semua catatan yang kamu kirim akan dihapus dan tidak bisa dikembalikan.",
      rkRename: 'Ganti nama panggilan',
      rkEmpty: 'Belum ada catatan',
      rkFirstMoveHint: 'Waktu mulai saat langkah pertama',
      rkAssistUsed: 'Bantuan dipakai, jadi tidak tercatat (kamu bisa lanjut berlatih)',
      rkPaused: 'Timer dijeda, jadi tidak tercatat (kamu bisa lanjut berlatih)',
      rkCancelled: 'Solve peringkat dibatalkan',
      rkViewRanking: 'Lihat peringkat',
      rkSave: 'Simpan',
      rkCancelBtn: 'Batal',
      rkMyBest: 'Rekor pribadi',
      rkNoRecordYet: 'Belum ada catatan',
      rkPlayers: 'Pemain: {n}',
      rkMoves: '{n} langkah',
      rkLeaveOk: "Hapus",
      rkRulesTitle: "Aturan",
      rkRuleInspL: "Inspeksi",
      rkRuleInspV: "Maks. 15 detik",
      rkRuleGuideL: "💡 Bantuan / OLL / PLL / ZBLL",
      rkRuleGuideV: "Tidak boleh",
      rkRulePauseL: "Jeda",
      rkRulePauseV: "Tidak bisa",
      rkFxFirst: "PERINGKAT 1 DUNIA!",
      rkFxTop: "PERINGKAT {n} DUNIA!",
      rkFxPb: "REKOR PRIBADI BARU!",
      rkFxTap: "Ketuk untuk lanjut",
      rkYou: "Kamu",
      rkReplayOpen: "Lihat cara peringkat {n} menyelesaikan",
      rkReplayScramble: "Acakan",
      rkReplayStartPos: "Setelah diacak",
      rkReplayDrag: "Geser untuk memutar 90° tiap kali",
      rkReplayTitle: "Tayangan ulang",
      rkModeRandomSize: "Mode Ukuran Acak",
      rkModeRandomSizeDesc: "Setiap putaran mengubah ukuran kubus secara acak antara 1% dan 160%",
      rkModeNormal: "Mode Normal",
      rkModeNormalDesc: "Kubus biasa — adu cepat saja",
      rkSeasonNow: "Bulan ini",
      rkSeasonEnded: "Selesai",
      rkSeasonEndedNote: "Bulan ini sudah selesai. Ayo tantang peringkat bulan ini!"
    },
    ru: {
      rkTitle: 'Мировой рейтинг',
      rkJoinTitle: 'Участвовать в мировом рейтинге',
      rkJoinBody:
        'Ваш никнейм и записи рейтинговых сборок попадут в мировой рейтинг.\n' +
        'Никакие другие данные не отправляются.\n' +
        'Выйти можно в любой момент — при выходе все записи удаляются.',
      rkRules: 'Правила: осмотр до 15 с / без 💡 Подсказки, OLL, PLL и ZBLL / без пауз',
      rkNickLabel: 'Никнейм (до 7 символов, виден в рейтинге)',
      rkNickBad: "Никнейм содержит недопустимые символы или выражения",
      rkNickLength: "Введите никнейм длиной от 1 до 7 символов",      rkJoin: 'Участвовать',
      rkNotNow: 'Не сейчас',
      rkStart: 'Начать рейтинговую сборку',
      rkInspection: 'Осмотр',
      rkSending: 'Отправка записи…',
      rkResultOk: 'Записано',
      rkRank: '{n}-е место',
      rkNewBest: 'Новый личный рекорд!',
      rkErrNotSolved: 'Кубик оказался не собран, поэтому запись не сохранена',
      rkErrInspection: 'Осмотр длился дольше 15 секунд, поэтому запись не сохранена',
      rkErrTime: 'Не удалось проверить время, поэтому запись не сохранена',
      rkErrExpired: 'Прошло слишком много времени — этот скрамбл завершён',
      rkErrOffline: 'Нет связи с сервером. Попробуйте ещё раз там, где есть сеть',
      rkErrTooSoon: 'Подождите немного и попробуйте снова',
      rkLeave: 'Выйти из рейтинга',
      rkLeaveConfirm: "Точно удалить себя из рейтинга? Все отправленные записи будут удалены без возможности восстановления.",
      rkRename: 'Сменить никнейм',
      rkEmpty: 'Записей пока нет',
      rkFirstMoveHint: 'Отсчёт начнётся с первого хода',
      rkAssistUsed: 'Была использована подсказка, поэтому запись не сохранится (можно продолжать тренировку)',
      rkPaused: 'Таймер ставили на паузу, поэтому запись не сохранится (можно продолжать тренировку)',
      rkCancelled: 'Рейтинговая сборка отменена',
      rkViewRanking: 'Открыть рейтинг',
      rkSave: 'Сохранить',
      rkCancelBtn: 'Отмена',
      rkMyBest: 'Личный рекорд',
      rkNoRecordYet: 'Записей пока нет',
      rkPlayers: 'Участников: {n}',
      rkMoves: '{n} ход.',
      rkLeaveOk: "Удалить",
      rkRulesTitle: "Правила",
      rkRuleInspL: "Осмотр",
      rkRuleInspV: "До 15 с",
      rkRuleGuideL: "💡 Подсказка / OLL / PLL / ZBLL",
      rkRuleGuideV: "Нельзя",
      rkRulePauseL: "Пауза",
      rkRulePauseV: "Нельзя",
      rkFxFirst: "№1 В МИРЕ!",
      rkFxTop: "№{n} В МИРЕ!",
      rkFxPb: "НОВЫЙ ЛИЧНЫЙ РЕКОРД!",
      rkFxTap: "Нажмите, чтобы продолжить",
      rkYou: "Вы",
      rkReplayOpen: "Как собирал №{n}",
      rkReplayScramble: "Скрамбл",
      rkReplayStartPos: "После скрамбла",
      rkReplayDrag: "Проведите, чтобы повернуть на 90°",
      rkReplayTitle: "Повтор сборки",
      rkModeRandomSize: "Режим случайного размера",
      rkModeRandomSizeDesc: "После каждого хода размер кубика случайно меняется от 1% до 160%",
      rkModeNormal: "Обычный режим",
      rkModeNormalDesc: "Обычный кубик — соревнуйтесь в скорости",
      rkSeasonNow: "Этот месяц",
      rkSeasonEnded: "Завершён",
      rkSeasonEndedNote: "Этот месяц завершён. Попробуйте рейтинг текущего месяца!"
    },
    'pt-BR': {
      rkTitle: 'Ranking Mundial',
      rkJoinTitle: 'Participar do Ranking Mundial',
      rkJoinBody:
        'Seu apelido e seus registros ranqueados entram no Ranking Mundial.\n' +
        'Nenhum outro dado é enviado.\n' +
        'Você pode sair quando quiser, e ao sair todos os registros são apagados.',
      rkRules: 'Regras: inspeção de 15 s / sem 💡 Ajuda, OLL, PLL ou ZBLL / sem pausa',
      rkNickLabel: 'Apelido (até 7 caracteres, aparece no ranking)',
      rkNickBad: "O apelido contém caracteres ou expressões que não podem ser usados",
      rkNickLength: "Digite um apelido de 1 a 7 caracteres",      rkJoin: 'Participar',
      rkNotNow: 'Agora não',
      rkStart: 'Começar partida ranqueada',
      rkInspection: 'Inspeção',
      rkSending: 'Enviando seu registro…',
      rkResultOk: 'Registrado',
      rkRank: '{n}º lugar',
      rkNewBest: 'Novo recorde pessoal!',
      rkErrNotSolved: 'O cubo não estava resolvido ao chegar, então não foi registrado',
      rkErrInspection: 'A inspeção passou de 15 segundos, então não foi registrado',
      rkErrTime: 'Não foi possível verificar o tempo, então não foi registrado',
      rkErrExpired: 'Passou tempo demais — este embaralhamento terminou',
      rkErrOffline: 'Não foi possível conectar ao servidor. Tente de novo onde houver sinal',
      rkErrTooSoon: 'Aguarde um pouco e tente de novo',
      rkLeave: 'Sair do ranking',
      rkLeaveConfirm: "Tem certeza de que quer se remover do ranking? Todos os registros enviados serão apagados e não poderão ser recuperados.",
      rkRename: 'Mudar apelido',
      rkEmpty: 'Ainda não há registros',
      rkFirstMoveHint: 'O tempo começa no primeiro movimento',
      rkAssistUsed: 'Você usou um guia, então não será registrado (pode continuar praticando)',
      rkPaused: 'O cronômetro foi pausado, então não será registrado (pode continuar praticando)',
      rkCancelled: 'Partida ranqueada cancelada',
      rkViewRanking: 'Ver ranking',
      rkSave: 'Salvar',
      rkCancelBtn: 'Cancelar',
      rkMyBest: 'Recorde pessoal',
      rkNoRecordYet: 'Ainda sem registro',
      rkPlayers: 'Jogadores: {n}',
      rkMoves: '{n} mov.',
      rkLeaveOk: "Remover",
      rkRulesTitle: "Regras",
      rkRuleInspL: "Inspeção",
      rkRuleInspV: "Até 15 s",
      rkRuleGuideL: "💡 Ajuda / OLL / PLL / ZBLL",
      rkRuleGuideV: "Não permitido",
      rkRulePauseL: "Pausa",
      rkRulePauseV: "Não permitida",
      rkFxFirst: "Nº 1 DO MUNDO!",
      rkFxTop: "Nº {n} DO MUNDO!",
      rkFxPb: "NOVO RECORDE PESSOAL!",
      rkFxTap: "Toque para continuar",
      rkYou: "Você",
      rkReplayOpen: "Ver como o nº {n} resolveu",
      rkReplayScramble: "Embaralhamento",
      rkReplayStartPos: "Recém-embaralhado",
      rkReplayDrag: "Deslize para girar 90° de cada vez",
      rkReplayTitle: "Replay",
      rkModeRandomSize: "Modo tamanho aleatório",
      rkModeRandomSizeDesc: "A cada giro, o cubo muda para um tamanho aleatório entre 1% e 160%",
      rkModeNormal: "Modo normal",
      rkModeNormalDesc: "Um cubo normal — é só ser rápido",
      rkSeasonNow: "Este mês",
      rkSeasonEnded: "Encerrado",
      rkSeasonEndedNote: "Este mês já terminou. Tente o ranking deste mês!"
    }
  };

  if (typeof I18N !== 'undefined' && I18N) {
    Object.keys(RANKED_I18N).forEach(function (lang) {
      if (!I18N[lang]) I18N[lang] = {};
      Object.keys(RANKED_I18N[lang]).forEach(function (k) {
        if (I18N[lang][k] === undefined) I18N[lang][k] = RANKED_I18N[lang][k];
      });
    });
  }
  global.RANKED_I18N = RANKED_I18N;
})(window);
