/* ZBLL_DATA — ZBLL 493種の手順表
   index.html から切り出したファイル。index.html の <script src="...">
   でこのファイルを先に読み込むので、ここでトップレベルに宣言した const は
   そのあとのスクリプトからそのまま参照できる。 */

    // --- ZBLL trainer ----------------------------------------------------
    // ZBLL solves the whole last layer in one algorithm, once the LL edges
    // are already oriented (i.e. after an edge-control F2L / ZBLS). All 493
    // cases are here, split into the eight standard families named after the
    // corner-orientation shape they show:
    //
    //   PLL (corners already oriented) 21, T 72, U 72, L 72, H 40,
    //   Pi 72, Sune 72, Anti-Sune 72  ->  493
    //
    // Each entry is:
    //   id      stable key, e.g. "ZBLL-Sune-07"
    //   name    what the panel prints, e.g. "Sune 07" / "PLL Ja"
    //   group   one of the eight families above
    //   cp      corner-permutation subtype, shown as the small second line
    //   alg     the solving algorithm (setup = the app runs it backwards)
    //   pattern 21 face letters for the recognition diagram: 3 back tabs,
    //           3 left, 3 right, 3 front, then the 3x3 top face read
    //           back-row-first. A letter names the face a sticker BELONGS
    //           to, exactly like PLL_DATA, so the sheet stays colour-neutral.
    //
    // The table was generated and verified programmatically against this
    // app's own move engine: every algorithm leaves the first two layers
    // untouched, every one returns its own setup to solved, the 493 produce
    // 493 distinct diagrams, and the family sizes match the canonical ZBLL
    // breakdown above.
const ZBLL_DATA = [
  {id:"ZBLL-PLL-01",name:"PLL Ub",group:"PLL",cp:"CP解決",alg:"R2 U R U R' U' R' U' R' U R'",pattern:"BBBLRLRFRFLFUUUUUUUUU"},
  {id:"ZBLL-PLL-02",name:"PLL Ua",group:"PLL",cp:"CP解決",alg:"R U' R U R U R U' R' U' R2",pattern:"BBBLFLRLRFRFUUUUUUUUU"},
  {id:"ZBLL-PLL-03",name:"PLL H",group:"PLL",cp:"CP解決",alg:"M2 U' M2 U2 M2 U' M2",pattern:"BFBLRLRLRFBFUUUUUUUUU"},
  {id:"ZBLL-PLL-04",name:"PLL T",group:"PLL",cp:"隣接2点交換",alg:"F R U' R' U R U R2 F' R U R U' R'",pattern:"BBRLRLFLBFFRUUUUUUUUU"},
  {id:"ZBLL-PLL-05",name:"PLL Gc",group:"PLL",cp:"隣接2点交換",alg:"R2 U' R U' R U R' U R2 U D' R U' R' D",pattern:"BRRLFLFLBFBRUUUUUUUUU"},
  {id:"ZBLL-PLL-06",name:"PLL Gd",group:"PLL",cp:"隣接2点交換",alg:"D' R U R' U' D R2 U' R U' R' U R' U R2",pattern:"BFRLRLFBBFLRUUUUUUUUU"},
  {id:"ZBLL-PLL-07",name:"PLL F",group:"PLL",cp:"隣接2点交換",alg:"R' U' R U' R' U R U R2 F' R U R U' R' F U R",pattern:"BFRLLLFRBFBRUUUUUUUUU"},
  {id:"ZBLL-PLL-08",name:"PLL Ga",group:"PLL",cp:"隣接2点交換",alg:"R2 U R' U R' U' R U' R2 U' D R' U R D'",pattern:"BFRLBLFLBFRRUUUUUUUUU"},
  {id:"ZBLL-PLL-09",name:"PLL Gb",group:"PLL",cp:"隣接2点交換",alg:"D R' U' R U D' R2 U R' U R U' R U' R2",pattern:"BLRLRLFFBFBRUUUUUUUUU"},
  {id:"ZBLL-PLL-10",name:"PLL Na",group:"PLL",cp:"対角2点交換",alg:"R U R' U2 R U R2 F' R U R U' R' F R U' R' U' R U' R'",pattern:"BBFLRRLLRBFFUUUUUUUUU"},
  {id:"ZBLL-PLL-11",name:"PLL E",group:"PLL",cp:"対角2点交換",alg:"F R' F' r U R U' R' r' U' R F R' U R U' F'",pattern:"BLFLFRLBRBRFUUUUUUUUU"},
  {id:"ZBLL-PLL-12",name:"PLL Aa",group:"PLL",cp:"3点交換",alg:"x R' U R' D2 R U' R' D2 x' R2",pattern:"RBRBLLFRLFFBUUUUUUUUU"},
  {id:"ZBLL-PLL-13",name:"PLL Ab",group:"PLL",cp:"3点交換",alg:"x R2 D2 R U R' D2 R U' x' R",pattern:"FBLRLLBRBFFRUUUUUUUUU"},
  {id:"ZBLL-PLL-14",name:"PLL Ja",group:"PLL",cp:"3点交換",alg:"L' U2 L U L' U2 R U' L U R' U'",pattern:"FLLRRLBBBFFRUUUUUUUUU"},
  {id:"ZBLL-PLL-15",name:"PLL Nb",group:"PLL",cp:"対角2点交換",alg:"R' U R' F R F' R U' R' F' U F R U R' U' R",pattern:"FBBRRLRLLFFBUUUUUUUUU"},
  {id:"ZBLL-PLL-16",name:"PLL V",group:"PLL",cp:"対角2点交換",alg:"R2 D' R2 U R2 U' D R D' R D R' U R U' R",pattern:"FRBRLLRBLFFBUUUUUUUUU"},
  {id:"ZBLL-PLL-17",name:"PLL Y",group:"PLL",cp:"対角2点交換",alg:"F R' F' R U R U' R' F R U' R' U R U R' F'",pattern:"FLBRBLRRLFFBUUUUUUUUU"},
  {id:"ZBLL-PLL-18",name:"PLL Z",group:"PLL",cp:"4点循環",alg:"U M U2 M2 U2 M U' M2 U' M2",pattern:"LBLFRFBLBRFRUUUUUUUUU"},
  {id:"ZBLL-PLL-19",name:"PLL Ra",group:"PLL",cp:"3点交換",alg:"R U2 R D R' U R D' R' U' R' U R U R'",pattern:"LBLFFRBLRBRFUUUUUUUUU"},
  {id:"ZBLL-PLL-20",name:"PLL Rb",group:"PLL",cp:"3点交換",alg:"R2 F R U R U' R' F' R U2 R' U2 R",pattern:"LLBFRFRBLRFBUUUUUUUUU"},
  {id:"ZBLL-PLL-21",name:"PLL Jb",group:"PLL",cp:"隣接2点交換",alg:"L U2 L' U' L U2 R' U L' U' R",pattern:"LLBFBBRRRLFFUUUUUUUUU"},
  {id:"ZBLL-T-01",name:"T 01",group:"T",cp:"CP解決",alg:"B' U' B U' B' U2 F B U F' U F U2 F'",pattern:"BBBLLURRULFRUUUUUUFUF"},
  {id:"ZBLL-T-02",name:"T 02",group:"T",cp:"CP解決",alg:"B' U' B U' B' U2 B L' U2 L U L' U L",pattern:"BBBLRURFULLRUUUUUUFUF"},
  {id:"ZBLL-T-03",name:"T 03",group:"T",cp:"CP解決",alg:"B' U' B U' B' U2 F B U2 F2 U' F2 U' F2 U2 F",pattern:"UBBBRFRFRULFLUUUUULUU"},
  {id:"ZBLL-T-04",name:"T 04",group:"T",cp:"CP解決",alg:"B U B' U B U2 B' R U2 R' U' R U' R'",pattern:"BBBLFURLULRRUUUUUUFUF"},
  {id:"ZBLL-T-05",name:"T 05",group:"T",cp:"CP解決",alg:"B U B' U B U2 F' B' U2 F2 U F2 U F2 U2 F'",pattern:"BBULFLBLFFRUUURUUUUUR"},
  {id:"ZBLL-T-06",name:"T 06",group:"T",cp:"CP解決",alg:"B U2 B' U' B U' B2 U2 B U B' U B",pattern:"URBBFFRBRULFLUUUUULUU"},
  {id:"ZBLL-T-07",name:"T 07",group:"T",cp:"CP解決",alg:"F' U2 F2 U F2 U F2 U2 F' B U B' U B U2 B'",pattern:"URBBLFRFRUBFLUUUUULUU"},
  {id:"ZBLL-T-08",name:"T 08",group:"T",cp:"CP解決",alg:"B U2 B' U' B U' B' L U L' U L U2 L'",pattern:"URBBBFRLRUFFLUUUUULUU"},
  {id:"ZBLL-T-09",name:"T 09",group:"T",cp:"CP解決",alg:"F U2 F2 U' F2 U' F2 U2 F B U B' U B U2 B'",pattern:"UFBBRFRLRUBFLUUUUULUU"},
  {id:"ZBLL-T-10",name:"T 10",group:"T",cp:"CP解決",alg:"B' U2 B U B' U B R' U' R U' R' U2 R",pattern:"BLULRLBBFFFUUURUUUUUR"},
  {id:"ZBLL-T-11",name:"T 11",group:"T",cp:"CP解決",alg:"F U2 F2 U' F2 U' F2 U2 F B' U' B U' B' U2 B",pattern:"BLULFLBRFFBUUURUUUUUR"},
  {id:"ZBLL-T-12",name:"T 12",group:"T",cp:"CP解決",alg:"B' U2 B U B' U B2 U2 B' U' B U' B'",pattern:"BLULBLBFFFRUUURUUUUUR"},
  {id:"ZBLL-T-13",name:"T 13",group:"T",cp:"隣接2点交換",alg:"L U L' U L U2 R' L' U L U' R U L'",pattern:"BRULLLRBRFFUUUFUUUUUB"},
  {id:"ZBLL-T-14",name:"T 14",group:"T",cp:"隣接2点交換",alg:"R' U2 R' D' R U2 R' D R U' R F R' U R U' F'",pattern:"ULRBFFFBBURRLUUUUULUU"},
  {id:"ZBLL-T-15",name:"T 15",group:"T",cp:"隣接2点交換",alg:"B' U2 B U B' U B R' U L U' R U L'",pattern:"BLULBLRRRFFUUUFUUUUUB"},
  {id:"ZBLL-T-16",name:"T 16",group:"T",cp:"3点交換",alg:"R' U2 R' D' R U2 R' D R2 r U R' U' r' F R F'",pattern:"UBRBLBFRFUFLLUUUUURUU"},
  {id:"ZBLL-T-17",name:"T 17",group:"T",cp:"3点交換",alg:"F' r U R' U' r' F U' R U' R' U2 R",pattern:"UBRBRBFFFULLLUUUUURUU"},
  {id:"ZBLL-T-18",name:"T 18",group:"T",cp:"3点交換",alg:"R' U2 R' D' R U2 R' D R2 U R' U L U' R U L'",pattern:"BFULRRRLLBBUUUFUUUUUF"},
  {id:"ZBLL-T-19",name:"T 19",group:"T",cp:"3点交換",alg:"F R' F' r U R U' R2 r' D' R U2 R' D R U2 R",pattern:"LBLULFURBRFRBUFUUUUUU"},
  {id:"ZBLL-T-20",name:"T 20",group:"T",cp:"3点交換",alg:"R U2 R' U' R U' R2 F' r U R U' r' F",pattern:"BRFLBULLUFFBUUUUUURUR"},
  {id:"ZBLL-T-21",name:"T 21",group:"T",cp:"3点交換",alg:"B' U2 B U B' U B R' U2 R' D' R U2 R' D R2",pattern:"BFFLLULBUFRBUUUUUURUR"},
  {id:"ZBLL-T-22",name:"T 22",group:"T",cp:"3点交換",alg:"F' U' F U' F' U2 F U R U' L' U R' U L U L' U L",pattern:"BFULLFFBRRRUUULUUUUUB"},
  {id:"ZBLL-T-23",name:"T 23",group:"T",cp:"3点交換",alg:"F' U' F U' F' U2 F R' F' r U R U' r' F",pattern:"BFFLBULRUFLBUUUUUURUR"},
  {id:"ZBLL-T-24",name:"T 24",group:"T",cp:"3点交換",alg:"R U2 R2 U' R2 U' R2 U2 F' r U R U' r' F",pattern:"BLULFFFRRRBUUULUUUUUB"},
  {id:"ZBLL-T-25",name:"T 25",group:"T",cp:"対角2点交換",alg:"R' U2 R' D' R U2 R' D R2 U R' U2 R' D' R U2 R' D R2",pattern:"BRFLBULFURLRUUUUUUBUF"},
  {id:"ZBLL-T-26",name:"T 26",group:"T",cp:"対角2点交換",alg:"R' F' r U R U' r' F2 U2 F' U' R' F U' F' U R",pattern:"LFLUBRULRBRFBUFUUUUUU"},
  {id:"ZBLL-T-27",name:"T 27",group:"T",cp:"対角2点交換",alg:"r U R' U' r' F R F' L U2 L' U' L U2 R' U L' U' R",pattern:"ULFBBBLRRUFFLUUUUURUU"},
  {id:"ZBLL-T-28",name:"T 28",group:"T",cp:"対角2点交換",alg:"L U2 L' U' L U2 R' U L' U' R F R' F' r U R U' r'",pattern:"LLLUBRURRBFFBUFUUUUUU"},
  {id:"ZBLL-T-29",name:"T 29",group:"T",cp:"対角2点交換",alg:"R' U' F U F' R U F U2 F2 r U R' U' r' F R",pattern:"ULFBRBLFRUBFLUUUUURUU"},
  {id:"ZBLL-T-30",name:"T 30",group:"T",cp:"隣接2点交換",alg:"R' U' R F R' U R U' F' U2 M U2 M2 U2 M U' M2 U' M2",pattern:"UBLRRFBLRUFFBUUUUULUU"},
  {id:"ZBLL-T-31",name:"T 31",group:"T",cp:"隣接2点交換",alg:"R2 U R U R' U' R' U' R' U R2 U' R F R' U R U' F'",pattern:"ULLRBFBRRUFFBUUUUULUU"},
  {id:"ZBLL-T-32",name:"T 32",group:"T",cp:"3点交換",alg:"R' F' r U R U' r' F",pattern:"RBUBLLRRBFFUUUFUUUUUL"},
  {id:"ZBLL-T-33",name:"T 33",group:"T",cp:"3点交換",alg:"M2 U' M2 U2 M2 U' R' M2 F' r U R U' r' F",pattern:"RFUBRLRLBFBUUUFUUUUUL"},
  {id:"ZBLL-T-34",name:"T 34",group:"T",cp:"3点交換",alg:"U2 M U2 M2 U2 M U' M2 U' R' M2 F' r U R U' r' F",pattern:"RLUBBLRFBFRUUUFUUUUUL"},
  {id:"ZBLL-T-35",name:"T 35",group:"T",cp:"4点循環",alg:"L' U2 L U L' U L2 U' R' U L' U' R F' U2 F U F' U F",pattern:"UBFRLRLFLURBBUUUUUFUU"},
  {id:"ZBLL-T-36",name:"T 36",group:"T",cp:"4点循環",alg:"B' U' B U' B' U2 B R U2 R' U' R U' R2 U L U' R U L'",pattern:"UBFRRRLLLUFBBUUUUUFUU"},
  {id:"ZBLL-T-37",name:"T 37",group:"T",cp:"4点循環",alg:"L' U2 L U L' U L2 U2 L' U' L U' R L' U' L' U R' U' L",pattern:"RBUBRFFLBRFUUULUUUUUL"},
  {id:"ZBLL-T-38",name:"T 38",group:"T",cp:"4点循環",alg:"L U2 L' U' L U' L2 U R U' L U R' B U2 B' U' B U' B'",pattern:"URFRLRLBLUFBBUUUUUFUU"},
  {id:"ZBLL-T-39",name:"T 39",group:"T",cp:"4点循環",alg:"R U' L' U R' U' R L U2 R' U' R U R' U' R U' R'",pattern:"RRFBFULLUFBLUUUUUURUB"},
  {id:"ZBLL-T-40",name:"T 40",group:"T",cp:"4点循環",alg:"L' U2 L U L' U L B' U' B U' B' U2 B R U' L' U R' U' L",pattern:"RFUBRFFBBRLUUULUUUUUL"},
  {id:"ZBLL-T-41",name:"T 41",group:"T",cp:"4点循環",alg:"L U2 L' U' L U' L2 U R U' L U R2 U' R U' R' U2 R",pattern:"UFFRLRLRLUBBBUUUUUFUU"},
  {id:"ZBLL-T-42",name:"T 42",group:"T",cp:"4点循環",alg:"R' U' F U F' R F U F' U' F U' F'",pattern:"BLLUBFURLRFBRUFUUUUUU"},
  {id:"ZBLL-T-43",name:"T 43",group:"T",cp:"4点循環",alg:"B' U' B U' B' U2 B L' U R U' L U R2 U' R U' R' U2 R",pattern:"ULFRBRLRLUFBBUUUUUFUU"},
  {id:"ZBLL-T-44",name:"T 44",group:"T",cp:"4点循環",alg:"L U2 L' U' L U' L' F U F' U F U2 F' R' U L U' R U L'",pattern:"RLUBRFFFBRBUUULUUUUUL"},
  {id:"ZBLL-T-45",name:"T 45",group:"T",cp:"3点交換",alg:"F' U2 F U F' U r U R' U' r' F R",pattern:"BLLUFBURRLBFRUFUUUUUU"},
  {id:"ZBLL-T-46",name:"T 46",group:"T",cp:"3点交換",alg:"F U2 F' U' F U' R' F' r U R U' r'",pattern:"RRBULLUFBFBRFULUUUUUU"},
  {id:"ZBLL-T-47",name:"T 47",group:"T",cp:"4点循環",alg:"B U B' U B U2 B' R U' L' U R' U' L2 U L' U L U2 L'",pattern:"FRURLRLBLBFUUUBUUUUUF"},
  {id:"ZBLL-T-48",name:"T 48",group:"T",cp:"4点循環",alg:"L U' R' U L' U' R2 U2 R' U' R U R' U' R U' R'",pattern:"RRBUFRULFBBLFULUUUUUU"},
  {id:"ZBLL-T-49",name:"T 49",group:"T",cp:"4点循環",alg:"L' U2 L U L' U L2 U2 L' U' L U' L2 U R U' L U R'",pattern:"UFLFLBBRFUBLRUUUUURUU"},
  {id:"ZBLL-T-50",name:"T 50",group:"T",cp:"4点循環",alg:"R' U' R U' R' U F U F' R F U' F'",pattern:"FLLRBUBRURFFUUUUUUBUL"},
  {id:"ZBLL-T-51",name:"T 51",group:"T",cp:"対角2点交換",alg:"R' F' r U R U' r' F2 R U' R' U R U R2 F' R U R U' R'",pattern:"FBURRLBLBFFUUURUUUUUL"},
  {id:"ZBLL-T-52",name:"T 52",group:"T",cp:"対角2点交換",alg:"R U R' U R U2 R2 F' r U R U' r' F L U' R' U L' U' R",pattern:"FFURBLBLBFRUUURUUUUUL"},
  {id:"ZBLL-T-53",name:"T 53",group:"T",cp:"対角2点交換",alg:"L U' R' U L' U' R F R' F' r U R U' r'",pattern:"ULBFFFRBLURBRUUUUULUU"},
  {id:"ZBLL-T-54",name:"T 54",group:"T",cp:"3点交換",alg:"F U F' U F U2 F' r U R' U' r' F R F'",pattern:"FFBRLURBUBRFUUUUUULUL"},
  {id:"ZBLL-T-55",name:"T 55",group:"T",cp:"3点交換",alg:"L' U2 L U L' U r L U R' U' r' F R F'",pattern:"FLBRRURBUBFFUUUUUULUL"},
  {id:"ZBLL-T-56",name:"T 56",group:"T",cp:"4点循環",alg:"F U F' U F U' R' U' R F' R' U R",pattern:"FLURBBFRRLFUUULUUUUUB"},
  {id:"ZBLL-T-57",name:"T 57",group:"T",cp:"3点交換",alg:"r U R' U' r' F R F'",pattern:"UBLLLBBRRUFFFUUUUURUU"},
  {id:"ZBLL-T-58",name:"T 58",group:"T",cp:"3点交換",alg:"M2 U' M2 U2 M2 U' r M2 U R' U' r' F R F'",pattern:"UFLLRBBLRUBFFUUUUURUU"},
  {id:"ZBLL-T-59",name:"T 59",group:"T",cp:"3点交換",alg:"R' U2 R' D' R U2 R' D R' U R' U R U2 R'",pattern:"FLBURRUBRBFFLULUUUUUU"},
  {id:"ZBLL-T-60",name:"T 60",group:"T",cp:"3点交換",alg:"U2 M U2 M2 U2 M U' M2 U' r M2 U R' U' r' F R F'",pattern:"ULLLBBBFRURFFUUUUURUU"},
  {id:"ZBLL-T-61",name:"T 61",group:"T",cp:"隣接2点交換",alg:"R U2 R2 U' R2 U' R2 U2 R L' U R U' L U R'",pattern:"FBRULBUFRLRFLUBUUUUUU"},
  {id:"ZBLL-T-62",name:"T 62",group:"T",cp:"隣接2点交換",alg:"U2 M U2 M2 U2 M U' M2 U' M2 F U F' R' F U' F' U R",pattern:"FBRURBULRLFFLUBUUUUUU"},
  {id:"ZBLL-T-63",name:"T 63",group:"T",cp:"隣接2点交換",alg:"B U2 B' U' B U' B' L U' R' U L' U' R",pattern:"URBLLLRBRUFFFUUUUUBUU"},
  {id:"ZBLL-T-64",name:"T 64",group:"T",cp:"隣接2点交換",alg:"R' U2 R2 U R2 U R2 U2 R' L U' R' U L' U' R",pattern:"LRBFLURBUBFRUUUUUULUF"},
  {id:"ZBLL-T-65",name:"T 65",group:"T",cp:"隣接2点交換",alg:"R U2 R2 U' R2 U' R2 U2 R L U' R' U L' U' R",pattern:"LFBFRURBUBLRUUUUUULUF"},
  {id:"ZBLL-T-66",name:"T 66",group:"T",cp:"隣接2点交換",alg:"F U F' R' F U' F' U R2 U' R U R U R U' R' U' R2",pattern:"FLRUBBURRLFFLUBUUUUUU"},
  {id:"ZBLL-T-67",name:"T 67",group:"T",cp:"隣接2点交換",alg:"R' U2 R2 U R2 U R2 U2 R' L' U R U' L U R'",pattern:"FLRURBUFRLBFLUBUUUUUU"},
  {id:"ZBLL-T-68",name:"T 68",group:"T",cp:"4点循環",alg:"F U R' U' R F' R' U' R U R' U R",pattern:"ULRLBBFRLUFBFUUUUURUU"},
  {id:"ZBLL-T-69",name:"T 69",group:"T",cp:"2組交換",alg:"R' U' R U' R' U F U F' R F U' F' L' U R U' L U R'",pattern:"LBUFRBRFRLLUUUFUUUUUB"},
  {id:"ZBLL-T-70",name:"T 70",group:"T",cp:"2組交換",alg:"R' U' F U F' R U F U2 F' R' U L U' R U L'",pattern:"LBUFFBRLRLRUUUFUUUUUB"},
  {id:"ZBLL-T-71",name:"T 71",group:"T",cp:"2組交換",alg:"R U' L' U R' U' R' L U' F U F' R F U F' U' F U' F'",pattern:"FBFUFBULBLRRLURUUUUUU"},
  {id:"ZBLL-T-72",name:"T 72",group:"T",cp:"2組交換",alg:"F R U' R' U R U R2 F' R U R U' R2 U' F U F' R F U' F'",pattern:"LLRFBUFFUBRBUUUUUULUR"},
  {id:"ZBLL-U-01",name:"U 01",group:"U",cp:"CP解決",alg:"F' U2 F U F' U F B U2 B' U' B U' B'",pattern:"BBBLLFRRFUFUUUUUUULUR"},
  {id:"ZBLL-U-02",name:"U 02",group:"U",cp:"CP解決",alg:"F U2 F2 U' F2 U' F2 U2 F B U2 B' U' B U' B'",pattern:"BBRLRLUFUFLRUUBUUUUUF"},
  {id:"ZBLL-U-03",name:"U 03",group:"U",cp:"CP解決",alg:"F' U2 F2 U F2 U F2 U2 F' B' U2 B U B' U B",pattern:"LBBUFURLRLRFBUUUUUFUU"},
  {id:"ZBLL-U-04",name:"U 04",group:"U",cp:"CP解決",alg:"F U F' U F U2 F' R U2 R2 U' R2 U' R2 U2 R",pattern:"UBUBFLBLRFRFLURUUUUUU"},
  {id:"ZBLL-U-05",name:"U 05",group:"U",cp:"CP解決",alg:"B' U' B U' B' U2 B2 U B' U B U2 B'",pattern:"LRBUFURBRLLFBUUUUUFUU"},
  {id:"ZBLL-U-06",name:"U 06",group:"U",cp:"CP解決",alg:"B U B' U B U2 B' L U2 L' U' L U' L'",pattern:"BRRLLLUFUFBRUUBUUUUUF"},
  {id:"ZBLL-U-07",name:"U 07",group:"U",cp:"CP解決",alg:"B' U' B U' B' U2 B R' U2 R2 U R2 U R2 U2 R'",pattern:"BRBLBFRLFUFUUUUUUULUR"},
  {id:"ZBLL-U-08",name:"U 08",group:"U",cp:"CP解決",alg:"B U2 B' U' B U' B' R U R' U R U2 R'",pattern:"UFUBLLBBRFRFLURUUUUUU"},
  {id:"ZBLL-U-09",name:"U 09",group:"U",cp:"CP解決",alg:"B' U2 B U B' U B L' U' L U' L' U2 L",pattern:"UFUBBLBRRFLFLURUUUUUU"},
  {id:"ZBLL-U-10",name:"U 10",group:"U",cp:"CP解決",alg:"B' U2 B U B' U F B U2 F2 U' F2 U' F2 U2 F",pattern:"BFRLRLULUFBRUUBUUUUUF"},
  {id:"ZBLL-U-11",name:"U 11",group:"U",cp:"CP解決",alg:"B' U' B U' B' U2 B R' U2 R U R' U R",pattern:"LLBUFURRRLBFBUUUUUFUU"},
  {id:"ZBLL-U-12",name:"U 12",group:"U",cp:"CP解決",alg:"B U B' U B U2 B2 U' B U' B' U2 B",pattern:"BLRLBLUFUFRRUUBUUUUUF"},
  {id:"ZBLL-U-13",name:"U 13",group:"U",cp:"隣接2点交換",alg:"F' r U R' U' r' F R2 U' L' U R' U' L",pattern:"BLRLFFUBURRFUUBUUUUUL"},
  {id:"ZBLL-U-14",name:"U 14",group:"U",cp:"隣接2点交換",alg:"F U2 F2 U' F2 U' F2 U2 F R' U L U' R U L'",pattern:"BBFLFLURUFLBUURUUUUUR"},
  {id:"ZBLL-U-15",name:"U 15",group:"U",cp:"隣接2点交換",alg:"L U' R' U L' U' R L' U' L U' L' U2 L",pattern:"UBUBFLRRBFLRLUFUUUUUU"},
  {id:"ZBLL-U-16",name:"U 16",group:"U",cp:"隣接2点交換",alg:"B U2 B' U' B U' B' R U' L' U R' U' L",pattern:"URUBLLRBBFFRLUFUUUUUU"},
  {id:"ZBLL-U-17",name:"U 17",group:"U",cp:"隣接2点交換",alg:"F' U2 F2 U F2 U F2 U2 F' R' U L U' R U L'",pattern:"BFFLRLUBUFLBUURUUUUUR"},
  {id:"ZBLL-U-18",name:"U 18",group:"U",cp:"隣接2点交換",alg:"L' U R U' L U R' L U L' U L U2 L'",pattern:"BLRLBFFRRUFUUUUUUULUB"},
  {id:"ZBLL-U-19",name:"U 19",group:"U",cp:"3点交換",alg:"F' r U R' U' r' F R2 U R' U R U2 R'",pattern:"BLFLRRUBUBFFUURUUUUUL"},
  {id:"ZBLL-U-20",name:"U 20",group:"U",cp:"3点交換",alg:"B' U' B U' B' U2 B R' U2 R' D' R U2 R' D R2",pattern:"URUBLFFFBRBRLULUUUUUU"},
  {id:"ZBLL-U-21",name:"U 21",group:"U",cp:"3点交換",alg:"L U' R' U L' U' R U' R2 D' R U2 R' D R U2 R",pattern:"BFFLRRLLRUBUUUUUUUFUB"},
  {id:"ZBLL-U-22",name:"U 22",group:"U",cp:"隣接2点交換",alg:"F' r U R' U' r' F R2 U R' U R U2 R2 U L U' R U L'",pattern:"RBLBFFBRFULUUUUUUULUR"},
  {id:"ZBLL-U-23",name:"U 23",group:"U",cp:"隣接2点交換",alg:"F R U' R' U R U R2 F' R U R U' R2 F' r U R U' r' F",pattern:"RBBBRLULUFFRUULUUUUUF"},
  {id:"ZBLL-U-24",name:"U 24",group:"U",cp:"2組交換",alg:"R' U2 R U R' U R2 U' L' U R' U' R' L U L U' R U L'",pattern:"BBLUFUBLFFRLRUUUUURUU"},
  {id:"ZBLL-U-25",name:"U 25",group:"U",cp:"2組交換",alg:"L' U R U' L U R2 U' R U' R' U2 R2 U' L' U R' U' L",pattern:"BRLULUBFFFBLRUUUUURUU"},
  {id:"ZBLL-U-26",name:"U 26",group:"U",cp:"2組交換",alg:"B' U' B U' B' U2 B R U' L' U R' U' R' L U L U' R U L'",pattern:"RRBBLFUFURBFUULUUUUUL"},
  {id:"ZBLL-U-27",name:"U 27",group:"U",cp:"2組交換",alg:"R U2 R' U' R U' R2 U L U' R U R L' U' L' U R' U' L",pattern:"BRLUBUBLFFFLRUUUUURUU"},
  {id:"ZBLL-U-28",name:"U 28",group:"U",cp:"2組交換",alg:"L U' R' U L' U' R F' U' F U' F' U2 F R' U L U' R U L'",pattern:"RRBBBFULURFFUULUUUUUL"},
  {id:"ZBLL-U-29",name:"U 29",group:"U",cp:"2組交換",alg:"L U' R' U L' U' R2 U R' U R U2 R2 U L U' R U L'",pattern:"BFLULUBBFFRLRUUUUURUU"},
  {id:"ZBLL-U-30",name:"U 30",group:"U",cp:"2組交換",alg:"B U B' U B U2 B' R U' L' U R' U' R' L U L U' R U L'",pattern:"BLLUFUBRFFBLRUUUUURUU"},
  {id:"ZBLL-U-31",name:"U 31",group:"U",cp:"2組交換",alg:"x U2 r' U' r U2 R' F R' F' x' R2 F U F' R' F U' F' R U' R' U2 R",pattern:"ULURBFLFFRRLBUBUUUUUU"},
  {id:"ZBLL-U-32",name:"U 32",group:"U",cp:"3点交換",alg:"L' U' L U' L' U L U' L' U2 R' L F' r U R U' r' F",pattern:"BLRURUFBLLFBRUUUUUFUU"},
  {id:"ZBLL-U-33",name:"U 33",group:"U",cp:"4点循環",alg:"B U B' U B U2 B2 U' B U' B' U2 B R' U L U' R U L'",pattern:"RBFBRRLLBUFUUUUUUUFUL"},
  {id:"ZBLL-U-34",name:"U 34",group:"U",cp:"4点循環",alg:"L U2 L' U' L U' R L' U R' U R U2 R2 U L U' R U L'",pattern:"RBLBRFULURFLUUFUUUUUB"},
  {id:"ZBLL-U-35",name:"U 35",group:"U",cp:"4点循環",alg:"R U' L' U R' U L U L' U L F' U' F U' F' U2 F",pattern:"URURLFFBLRFBBULUUUUUU"},
  {id:"ZBLL-U-36",name:"U 36",group:"U",cp:"4点循環",alg:"F U F' R' F U' F' U R2 U2 R2 U' R2 U' R2 U2 R",pattern:"RRFBLRLBBUFUUUUUUUFUL"},
  {id:"ZBLL-U-37",name:"U 37",group:"U",cp:"4点循環",alg:"B U B' U B U2 B2 U' B U' B' U2 B R U' L' U R' U' L",pattern:"UFURLFFRLRBBBULUUUUUU"},
  {id:"ZBLL-U-38",name:"U 38",group:"U",cp:"4点循環",alg:"B U B' U B U2 B' R U R' U R U2 R2 U L U' R U L'",pattern:"BFFULULRLFBBRUUUUURUU"},
  {id:"ZBLL-U-39",name:"U 39",group:"U",cp:"4点循環",alg:"L' U' L U' L' U2 L2 U' R' U L' U' R F' U' F U' F' U2 F",pattern:"BFFUBULLLFRBRUUUUURUU"},
  {id:"ZBLL-U-40",name:"U 40",group:"U",cp:"3点交換",alg:"R U2 R' U' R U' R D' R U2 R' D R U2 R",pattern:"BRFUBULLRBFFRUUUUULUU"},
  {id:"ZBLL-U-41",name:"U 41",group:"U",cp:"3点交換",alg:"B' U2 B U B' U F' B r U R' U' r' F R",pattern:"BFFULULBRBRFRUUUUULUU"},
  {id:"ZBLL-U-42",name:"U 42",group:"U",cp:"3点交換",alg:"F' U' F U' F' U2 r U R' U' r' F R",pattern:"RFFBBLLRFULUUUUUUUBUR"},
  {id:"ZBLL-U-43",name:"U 43",group:"U",cp:"3点交換",alg:"F' U' F U' F' U2 F R2 D' R U2 R' D R U2 R",pattern:"BFFUBULRRBLFRUUUUULUU"},
  {id:"ZBLL-U-44",name:"U 44",group:"U",cp:"3点交換",alg:"L' U2 L U L' U R2 L D' R U2 R' D R U2 R",pattern:"RLLBRBUBULFRUUFUUUUUF"},
  {id:"ZBLL-U-45",name:"U 45",group:"U",cp:"3点交換",alg:"R2 D' R U2 R' D R U2 R",pattern:"UBUFLLLRBFFRRUBUUUUUU"},
  {id:"ZBLL-U-46",name:"U 46",group:"U",cp:"3点交換",alg:"R' U2 R' D' R U2 R' D R F' r U R U' r' F",pattern:"FBBRLLURUFFBUULUUUUUR"},
  {id:"ZBLL-U-47",name:"U 47",group:"U",cp:"3点交換",alg:"F U F' U F U2 R' F' r U R U' r'",pattern:"FFLRLFBBRURUUUUUUULUB"},
  {id:"ZBLL-U-48",name:"U 48",group:"U",cp:"3点交換",alg:"B U2 B' U' B U' F B' R' F' r U R U' r'",pattern:"FFBRBLURUFLBUULUUUUUR"},
  {id:"ZBLL-U-49",name:"U 49",group:"U",cp:"3点交換",alg:"R2 D' R U2 R' D R U2 R M2 U' M2 U2 M2 U' M2",pattern:"UFUFRLLLBFBRRUBUUUUUU"},
  {id:"ZBLL-U-50",name:"U 50",group:"U",cp:"4点循環",alg:"L' U2 L U L' U R' L U L U' R U' L' U' L U' L'",pattern:"UBUFLRLFFBRLRUBUUUUUU"},
  {id:"ZBLL-U-51",name:"U 51",group:"U",cp:"4点循環",alg:"L U2 L' U' L U' L' F U2 F' U' F U' F' L U' R' U L' U' R",pattern:"FBBRRRULUBFFUULUUUUUL"},
  {id:"ZBLL-U-52",name:"U 52",group:"U",cp:"4点循環",alg:"B U2 B' U' B U' F' B' U' F U' F' U2 F L U' R' U L' U' R",pattern:"FFBRRRUBUBLFUULUUUUUL"},
  {id:"ZBLL-U-53",name:"U 53",group:"U",cp:"4点循環",alg:"L' U2 L U L' U R L U' L' U R' U L U L' U L",pattern:"UFUFLRLRFBBLRUBUUUUUU"},
  {id:"ZBLL-U-54",name:"U 54",group:"U",cp:"4点循環",alg:"B U B' U B U2 F B' U2 F' U' F U' F' L U' R' U L' U' R",pattern:"RFLULUBRFRBLFUUUUUBUU"},
  {id:"ZBLL-U-55",name:"U 55",group:"U",cp:"4点循環",alg:"F' U2 F U F' U F L U2 L' U' L U' L2 U R U' L U R'",pattern:"RFLUBUBLFRRLFUUUUUBUU"},
  {id:"ZBLL-U-56",name:"U 56",group:"U",cp:"4点循環",alg:"L' U R U' L U' R' U' R U' R' F U F' U F U2 F'",pattern:"ULUFBRLRFBFLRUBUUUUUU"},
  {id:"ZBLL-U-57",name:"U 57",group:"U",cp:"3点交換",alg:"R U R' U R U' R' U R U2 R' r U R' U' r' F R F'",pattern:"LRBFBRULUBFRUULUUUUUF"},
  {id:"ZBLL-U-58",name:"U 58",group:"U",cp:"3点交換",alg:"R' F' r U R U' r' F R' U2 R2 U R2 U R2 U2 R'",pattern:"FFLUBUBRRRLFLUUUUUBUU"},
  {id:"ZBLL-U-59",name:"U 59",group:"U",cp:"3点交換",alg:"F R' F' r U R U' r' L' U' L U' L' U2 L",pattern:"FRBUBURLLFFBLUUUUURUU"},
  {id:"ZBLL-U-60",name:"U 60",group:"U",cp:"隣接2点交換",alg:"L' U' L U' L' U2 L2 U' R' U L' U' R",pattern:"LBBFLLRFFURUUUUUUUBUR"},
  {id:"ZBLL-U-61",name:"U 61",group:"U",cp:"隣接2点交換",alg:"F' U2 F2 U F2 U F2 U2 F' L U' R' U L' U' R",pattern:"FBBULURFRBRFLUUUUULUU"},
  {id:"ZBLL-U-62",name:"U 62",group:"U",cp:"隣接2点交換",alg:"L U L' U L U2 L2 U R U' L U R'",pattern:"URULLBBBRLFFFURUUUUUU"},
  {id:"ZBLL-U-63",name:"U 63",group:"U",cp:"隣接2点交換",alg:"r U R' U' r' F R U R' U' R F' R' U R",pattern:"FRBUBURFRBLFLUUUUULUU"},
  {id:"ZBLL-U-64",name:"U 64",group:"U",cp:"隣接2点交換",alg:"F U2 F2 U' F2 U' F2 U2 F L U' R' U L' U' R",pattern:"FFBUBURLRBRFLUUUUULUU"},
  {id:"ZBLL-U-65",name:"U 65",group:"U",cp:"隣接2点交換",alg:"R U2 R' U' R U R' U' R U' R' U' R' F' r U R U' r' F",pattern:"UFULBBBLRLRFFURUUUUUU"},
  {id:"ZBLL-U-66",name:"U 66",group:"U",cp:"隣接2点交換",alg:"R' U' R F R' U R U' R' F' r U R U' r'",pattern:"FLBUFURBRBRFLUUUUULUU"},
  {id:"ZBLL-U-67",name:"U 67",group:"U",cp:"隣接2点交換",alg:"B' U2 B U B' U B L' U R U' L U R'",pattern:"ULULBBBRRLFFFURUUUUUU"},
  {id:"ZBLL-U-68",name:"U 68",group:"U",cp:"4点循環",alg:"R2 D' R U2 R' D R U2 R L U' R' U L' U' R",pattern:"FLRUFUFBLRRBLUUUUUBUU"},
  {id:"ZBLL-U-69",name:"U 69",group:"U",cp:"2組交換",alg:"R U' L' U R' U' R' L U L U' R U L'",pattern:"LBRFLLFRRUFUUUUUUUBUB"},
  {id:"ZBLL-U-70",name:"U 70",group:"U",cp:"2組交換",alg:"F U F' R' F U' F' R U' R' U2 R2 U' L' U R' U' L",pattern:"FRRULUFFBBBRLUUUUULUU"},
  {id:"ZBLL-U-71",name:"U 71",group:"U",cp:"2組交換",alg:"R' F' r U R U' r' F U2 R2 D' R U2 R' D R U2 R",pattern:"LFRFRLFLRUBUUUUUUUBUB"},
  {id:"ZBLL-U-72",name:"U 72",group:"U",cp:"2組交換",alg:"F R U' R' U R U R2 F' R U R U' R' U' R' U2 R' D' R U2 R' D R2",pattern:"LLRFBLFFRURUUUUUUUBUB"},
  {id:"ZBLL-L-01",name:"L 01",group:"L",cp:"CP解決",alg:"B' U' B U' B' U2 B R U R' U R U2 R'",pattern:"BBULRUBFRLLFUURUUUFUU"},
  {id:"ZBLL-L-02",name:"L 02",group:"L",cp:"CP解決",alg:"B U B' U B U2 B' L' U' L U' L' U2 L",pattern:"UBBBFLRLUFRRLUUUUUUUF"},
  {id:"ZBLL-L-03",name:"L 03",group:"L",cp:"CP解決",alg:"B U2 B' U' B U' F B' U F' U F U2 F'",pattern:"URBBFLRBUFLRLUUUUUUUF"},
  {id:"ZBLL-L-04",name:"L 04",group:"L",cp:"CP解決",alg:"B' U' B U' B' U2 F' B U2 F U F' U F",pattern:"BRULFUBBRLLFUURUUUFUU"},
  {id:"ZBLL-L-05",name:"L 05",group:"L",cp:"CP解決",alg:"B U2 B' U' B U' B' L' U2 L U L' U L",pattern:"UFBBLLRBUFRRLUUUUUUUF"},
  {id:"ZBLL-L-06",name:"L 06",group:"L",cp:"CP解決",alg:"B' U2 B U B' U B R U2 R' U' R U' R'",pattern:"BFULBUBRRLLFUURUUUFUU"},
  {id:"ZBLL-L-07",name:"L 07",group:"L",cp:"隣接2点交換",alg:"L' U R U' L U R2 F' r U R U' r' F",pattern:"BRULBUBFFFLLUURUUURUU"},
  {id:"ZBLL-L-08",name:"L 08",group:"L",cp:"隣接2点交換",alg:"L' U2 L U L' U R' L U L U' R U L'",pattern:"LBRUFLFRRFLUBUUUUUUUB"},
  {id:"ZBLL-L-09",name:"L 09",group:"L",cp:"隣接2点交換",alg:"B' U' B U' B' U2 B R U' L' U R' U' L",pattern:"BBULFURRBLLRUUFUUUFUU"},
  {id:"ZBLL-L-10",name:"L 10",group:"L",cp:"隣接2点交換",alg:"L U2 L' U' L U' R L' U' L' U R' U' L",pattern:"BLULBURRBLFRUUFUUUFUU"},
  {id:"ZBLL-L-11",name:"L 11",group:"L",cp:"隣接2点交換",alg:"U2 M U2 M2 U2 M U' M2 U' M2 F U R' U' R F' R' U R",pattern:"RBUBRULLRLFFUUBUUUFUU"},
  {id:"ZBLL-L-12",name:"L 12",group:"L",cp:"隣接2点交換",alg:"F U R' U' R F' R' U' R U R' U' R U R' U R",pattern:"BFLUBLBLFFRURUUUUUUUR"},
  {id:"ZBLL-L-13",name:"L 13",group:"L",cp:"2組交換",alg:"B U2 B' U' B U' B' R' U L U' R U R' L' U L U' R U L'",pattern:"BBLUFFBLLRRURUUUUUUUF"},
  {id:"ZBLL-L-14",name:"L 14",group:"L",cp:"2組交換",alg:"R U R' U R U2 R2 U L U' R U R' L' U L U' R U L'",pattern:"RRUBLULFFFBLUUBUUURUU"},
  {id:"ZBLL-L-15",name:"L 15",group:"L",cp:"2組交換",alg:"R' U' R U' R' U' L U' R U R' L' U L U' R U L'",pattern:"BFLULFBBLRRURUUUUUUUF"},
  {id:"ZBLL-L-16",name:"L 16",group:"L",cp:"2組交換",alg:"R2 D' R U2 R' D R U2 R U L' U R U' L U R'",pattern:"RFBBRRULFUBLUULUUUFUU"},
  {id:"ZBLL-L-17",name:"L 17",group:"L",cp:"2組交換",alg:"R U R' U R U L' U R' U' R' L U L U' R U L'",pattern:"BLLURFBBLRFURUUUUUUUF"},
  {id:"ZBLL-L-18",name:"L 18",group:"L",cp:"3点交換",alg:"R' U2 R' D' R U2 R' D R2",pattern:"UBRRLLFRUFFLBUUUUUUUB"},
  {id:"ZBLL-L-19",name:"L 19",group:"L",cp:"3点交換",alg:"r U R' U' r' F R U2 F' U' F U' F'",pattern:"RRUBLURFLLBBUUFUUUFUU"},
  {id:"ZBLL-L-20",name:"L 20",group:"L",cp:"3点交換",alg:"R' U2 R U R' U R U' L' U' L U' L' U' R U' L U R'",pattern:"BRRUBLFLBFFURUUUUUUUL"},
  {id:"ZBLL-L-21",name:"L 21",group:"L",cp:"3点交換",alg:"r U R' U' r' F R U F' U F U2 F'",pattern:"BFRULLFBBFRURUUUUUUUL"},
  {id:"ZBLL-L-22",name:"L 22",group:"L",cp:"3点交換",alg:"R' U2 R' D' R U2 R' D R2 M2 U' M2 U2 M2 U' M2",pattern:"UFRRRLFLUFBLBUUUUUUUB"},
  {id:"ZBLL-L-23",name:"L 23",group:"L",cp:"4点循環",alg:"L U L' U L U R' U L' U' R L' U' L U' L' U2 L",pattern:"UBFRLFLFURRLBUUUUUUUB"},
  {id:"ZBLL-L-24",name:"L 24",group:"L",cp:"4点循環",alg:"B' U2 B U B' U B2 U2 B' U' B U' B' R' U L U' R U L'",pattern:"RBLBRRULLUFBUUFUUUFUU"},
  {id:"ZBLL-L-25",name:"L 25",group:"L",cp:"4点循環",alg:"L' U' L U' L' U' R U' L U R' L U L' U L U2 L'",pattern:"RRLBLRUBLUFBUUFUUUFUU"},
  {id:"ZBLL-L-26",name:"L 26",group:"L",cp:"4点循環",alg:"L U L' U L U' L' U L U2 R' L' U L U' R U L'",pattern:"BRFUFFLLBRBURUUUUUUUL"},
  {id:"ZBLL-L-27",name:"L 27",group:"L",cp:"4点循環",alg:"R U R' U R U' R' U R U2 R2 U L U' R U L'",pattern:"BFFURFLBBRLURUUUUUUUL"},
  {id:"ZBLL-L-28",name:"L 28",group:"L",cp:"4点循環",alg:"F U2 F' U' F U' F2 U2 F U F' U F R' U L U' R U L'",pattern:"RFLBLRURLUBBUUFUUUFUU"},
  {id:"ZBLL-L-29",name:"L 29",group:"L",cp:"4点循環",alg:"B' U2 B U B' U B2 U2 B' U' B U' B' R U' L' U R' U' L",pattern:"UFFRLFLRURBLBUUUUUUUB"},
  {id:"ZBLL-L-30",name:"L 30",group:"L",cp:"4点循環",alg:"F U F' R' F U' F' R U' R' U2 R",pattern:"UFFRBFLLURRLBUUUUUUUB"},
  {id:"ZBLL-L-31",name:"L 31",group:"L",cp:"4点循環",alg:"B' U2 B U B' U' B U B' U B R' U L U' R U L'",pattern:"BFFUBFLLBRRURUUUUUUUL"},
  {id:"ZBLL-L-32",name:"L 32",group:"L",cp:"4点循環",alg:"F U F' R' F U' F' U' R U R' U R",pattern:"RLUBBUFRLFFBUULUUURUU"},
  {id:"ZBLL-L-33",name:"L 33",group:"L",cp:"3点交換",alg:"F R' F' r U R U' r'",pattern:"RBLBLLURRUFFUUFUUUBUU"},
  {id:"ZBLL-L-34",name:"L 34",group:"L",cp:"3点交換",alg:"M2 U' M2 U2 M2 U' M2 F R' F' r U R U' r'",pattern:"RFLBRLULRUBFUUFUUUBUU"},
  {id:"ZBLL-L-35",name:"L 35",group:"L",cp:"3点交換",alg:"F R' F' r U R U' R r' U2 R' U' R U R' U' R U' R'",pattern:"BLFURBLBFLFURUUUUUUUR"},
  {id:"ZBLL-L-36",name:"L 36",group:"L",cp:"3点交換",alg:"U2 M U2 M2 U2 M U' M2 U' M2 F R' F' r U R U' r'",pattern:"RLLBBLUFRURFUUFUUUBUU"},
  {id:"ZBLL-L-37",name:"L 37",group:"L",cp:"3点交換",alg:"F' r U R' U' r' F R",pattern:"RBLULLBRRFFUFUUUUUUUB"},
  {id:"ZBLL-L-38",name:"L 38",group:"L",cp:"3点交換",alg:"M2 U' M2 U2 M2 U' M2 F' r U R' U' r' F R",pattern:"RFLURLBLRFBUFUUUUUUUB"},
  {id:"ZBLL-L-39",name:"L 39",group:"L",cp:"4点循環",alg:"B U2 B' U' B U' B' L U L' U L U R' U L' U' R",pattern:"RBLULRBFLBRUFUUUUUUUF"},
  {id:"ZBLL-L-40",name:"L 40",group:"L",cp:"4点循環",alg:"B U2 B' U' B U' B2 U2 B U B' U B L U' R' U L' U' R",pattern:"RBLURRBLLBFUFUUUUUUUF"},
  {id:"ZBLL-L-41",name:"L 41",group:"L",cp:"4点循環",alg:"R' U2 R2 U R2 U R2 U2 R2 U' F U F' R F U' F'",pattern:"RRLULRBBLBFUFUUUUUUUF"},
  {id:"ZBLL-L-42",name:"L 42",group:"L",cp:"4点循環",alg:"F' U2 F U F' U F L' U' L U' L' U' R U' L U R'",pattern:"FRURLULBFRFLUUBUUUBUU"},
  {id:"ZBLL-L-43",name:"L 43",group:"L",cp:"4点循環",alg:"L' U' L U' L' U2 L2 U L' U L U R' U L' U' R",pattern:"UFLFLRBRUBBFRUUUUUUUL"},
  {id:"ZBLL-L-44",name:"L 44",group:"L",cp:"4点循環",alg:"F U F' U F U' F' R' F U' F' U R",pattern:"FLBRBBURFUFLUULUUURUU"},
  {id:"ZBLL-L-45",name:"L 45",group:"L",cp:"対角2点交換",alg:"D' R U R' U' D R2 U' R U' R' U R' U D' R U2 R' D R U2 R",pattern:"UFBFRLRBUFLLRUUUUUUUB"},
  {id:"ZBLL-L-46",name:"L 46",group:"L",cp:"対角2点交換",alg:"D R' U' R U D' R2 U R' U R U' R U' D' R U2 R' D R U2 R",pattern:"ULBFRLRFUFBLRUUUUUUUB"},
  {id:"ZBLL-L-47",name:"L 47",group:"L",cp:"3点交換",alg:"U' R' U' R U' R' U R U' R' U2 R2 U' L' U R' U' L",pattern:"URBFBBRLULFFRUUUUUUUL"},
  {id:"ZBLL-L-48",name:"L 48",group:"L",cp:"2組交換",alg:"R U R' U R U' R' U R U' R' U R U2 R'",pattern:"FBURLUFRLRFBUULUUUBUU"},
  {id:"ZBLL-L-49",name:"L 49",group:"L",cp:"2組交換",alg:"R U2 R' U' R U R' U' R U' R' L' U2 L U L' U L",pattern:"URFFBRLLUBFLRUUUUUUUB"},
  {id:"ZBLL-L-50",name:"L 50",group:"L",cp:"2組交換",alg:"R U R' U R U' R' U R U2 R2 U' R U' R' U2 R",pattern:"RFFUBRLRBBLUFUUUUUUUL"},
  {id:"ZBLL-L-51",name:"L 51",group:"L",cp:"2組交換",alg:"F U F' R' F U' F' U2 L U' R U L'",pattern:"UFFFRRLLUBBLRUUUUUUUB"},
  {id:"ZBLL-L-52",name:"L 52",group:"L",cp:"2組交換",alg:"R U R' U R U' R' U R U2 R' L' U' L U' L' U2 L",pattern:"ULFFRRLBUBFLRUUUUUUUB"},
  {id:"ZBLL-L-53",name:"L 53",group:"L",cp:"2組交換",alg:"R' U2 R U R' U R2 U2 R' U' R U R' U' R U' R'",pattern:"RLFUFRLRBBBUFUUUUUUUL"},
  {id:"ZBLL-L-54",name:"L 54",group:"L",cp:"4点循環",alg:"F U2 F2 U' F2 U' F2 U2 F2 U R' U' R F' R' U R",pattern:"UBFFFBLRULLBRUUUUUUUR"},
  {id:"ZBLL-L-55",name:"L 55",group:"L",cp:"4点循環",alg:"R' U L U' R U R' L' U2 R' D' R U2 R' D R2",pattern:"FRURBUFFBBLRUULUUULUU"},
  {id:"ZBLL-L-56",name:"L 56",group:"L",cp:"4点循環",alg:"R' U' R U' R' U R F R' U R U' F'",pattern:"FLLRBLURBUFRUUFUUUBUU"},
  {id:"ZBLL-L-57",name:"L 57",group:"L",cp:"3点交換",alg:"R' F' r U R U' r' U' F U' F' U2 F",pattern:"LFBFBBURRULFUULUUURUU"},
  {id:"ZBLL-L-58",name:"L 58",group:"L",cp:"3点交換",alg:"R U2 R' U' R U R' U' R U' R' U R U' L' U R' U' L",pattern:"FLLURRBBFBFULUUUUUUUR"},
  {id:"ZBLL-L-59",name:"L 59",group:"L",cp:"3点交換",alg:"R' F' r U R U' r' U2 F U F' U F",pattern:"ULLLFRBRUBBRFUUUUUUUF"},
  {id:"ZBLL-L-60",name:"L 60",group:"L",cp:"3点交換",alg:"L' U R U' L U R' U' F' U2 F2 U F2 U F2 U2 F'",pattern:"URBLBFRLURFLFUUUUUUUB"},
  {id:"ZBLL-L-61",name:"L 61",group:"L",cp:"3点交換",alg:"L' U R U' L U R' U' F U2 F2 U' F2 U' F2 U2 F",pattern:"ULBLRFRBURFLFUUUUUUUB"},
  {id:"ZBLL-L-62",name:"L 62",group:"L",cp:"隣接2点交換",alg:"B U B' U B U2 B' L' U R U' L U R'",pattern:"UBBLLBRFULRRFUUUUUUUF"},
  {id:"ZBLL-L-63",name:"L 63",group:"L",cp:"隣接2点交換",alg:"R U' L' U R' U' R' L U2 R2 U R2 U R2 U2 R'",pattern:"LBUFLUBFRBRFUURUUULUU"},
  {id:"ZBLL-L-64",name:"L 64",group:"L",cp:"隣接2点交換",alg:"R U' L' U R' U' R L U2 R2 U' R2 U' R2 U2 R",pattern:"LFUFBUBLRBRFUURUUULUU"},
  {id:"ZBLL-L-65",name:"L 65",group:"L",cp:"4点循環",alg:"U2 M U2 M2 U2 M U' M2 U' M2 U F R' F' r U R U' r'",pattern:"UBRLRRFLUBFLFUUUUUUUB"},
  {id:"ZBLL-L-66",name:"L 66",group:"L",cp:"4点循環",alg:"R' U' R F R' U R U F' U' F U' F'",pattern:"LLUFBURRLRFBUUFUUUBUU"},
  {id:"ZBLL-L-67",name:"L 67",group:"L",cp:"4点循環",alg:"R' U' R F R' U R F' U F U2 F'",pattern:"FLRURRFFBBBULUUUUUUUL"},
  {id:"ZBLL-L-68",name:"L 68",group:"L",cp:"2組交換",alg:"L U' R' U L' U' R U R' U2 R' D' R U2 R' D R2",pattern:"UBRLLBFRULFBFUUUUUUUR"},
  {id:"ZBLL-L-69",name:"L 69",group:"L",cp:"2組交換",alg:"R' U2 R' D' R U2 R' D R U' R U' R' U2 R F' r U R' U' r' F R",pattern:"LBFFRLUFBULRUURUUUBUU"},
  {id:"ZBLL-L-70",name:"L 70",group:"L",cp:"2組交換",alg:"R' U' F U F' R F U' R U' R' U R U R2 F' R U R U' R'",pattern:"LRUFFURBBBLRUUFUUULUU"},
  {id:"ZBLL-L-71",name:"L 71",group:"L",cp:"2組交換",alg:"D' R U R' U' D R2 U' R U' R' U R' U R2 F U F' R' F U' F' U R",pattern:"FLRUFBFRRLBULUUUUUUUB"},
  {id:"ZBLL-L-72",name:"L 72",group:"L",cp:"2組交換",alg:"F R U' R' U R U R2 F' R U R U' R' U' R' F' r U R U' r' F",pattern:"LLUFBURFBBRRUUFUUULUU"},
  {id:"ZBLL-H-01",name:"H 01",group:"H",cp:"CP解決",alg:"L U L' U L U' L' U L U2 L'",pattern:"LBRURUUFULLRBUBUUUFUF"},
  {id:"ZBLL-H-02",name:"H 02",group:"H",cp:"CP解決",alg:"L U2 L' U' L U L' U' L U' L'",pattern:"UBUBFFBLFURULURUUULUR"},
  {id:"ZBLL-H-03",name:"H 03",group:"H",cp:"CP解決",alg:"B' U2 B U B' U B L U L' U L U2 L'",pattern:"LRRUFUUBULLRBUBUUUFUF"},
  {id:"ZBLL-H-04",name:"H 04",group:"H",cp:"CP解決",alg:"B' U2 B U B' U' B U B' U B",pattern:"LRRULUUFULBRBUBUUUFUF"},
  {id:"ZBLL-H-05",name:"H 05",group:"H",cp:"CP解決",alg:"B' U' B U' B' U B U' B' U2 B",pattern:"UFUBLFBBFURULURUUULUR"},
  {id:"ZBLL-H-06",name:"H 06",group:"H",cp:"CP解決",alg:"F' r U R' U' r' F R U' L U' R' U L' U' R",pattern:"LFRURUULULBRBUBUUUFUF"},
  {id:"ZBLL-H-07",name:"H 07",group:"H",cp:"CP解決",alg:"B U2 B' U' B U' B' R' U' R U' R' U2 R",pattern:"LLRUBUUFULRRBUBUUUFUF"},
  {id:"ZBLL-H-08",name:"H 08",group:"H",cp:"隣接2点交換",alg:"R' U' R F R' U R U' F2 r U R' U' r' F R",pattern:"ULUBFFRBRURULUFUUULUB"},
  {id:"ZBLL-H-09",name:"H 09",group:"H",cp:"隣接2点交換",alg:"B U2 B' U' B U' B' R' U L U' R U L'",pattern:"LLFURUUFULBBBURUUUFUR"},
  {id:"ZBLL-H-10",name:"H 10",group:"H",cp:"3点交換",alg:"F' r U R' U' r' F R2 U2 R' U' R U' R'",pattern:"URUBBBRLLUFULUFUUURUF"},
  {id:"ZBLL-H-11",name:"H 11",group:"H",cp:"3点交換",alg:"R U R' U R U2 R' r U R' U' r' F R U2 F' U' F U' F'",pattern:"ULUBFRFRRUBULULUUUFUB"},
  {id:"ZBLL-H-12",name:"H 12",group:"H",cp:"隣接2点交換",alg:"F U R' U' R F' U' R' U2 R F U2 F' U' F U' F'",pattern:"UBURRFLLFUFUBUBUUULUR"},
  {id:"ZBLL-H-13",name:"H 13",group:"H",cp:"3点交換",alg:"r U R' U' r' F R U2 F2 U' F2 U' F2 U2 F",pattern:"BLFURUUBULFLRURUUUFUB"},
  {id:"ZBLL-H-14",name:"H 14",group:"H",cp:"3点交換",alg:"B U2 B' U' B U' F' B' r U R' U' r' F R",pattern:"UFURBLFRFULUBULUUUBUR"},
  {id:"ZBLL-H-15",name:"H 15",group:"H",cp:"3点交換",alg:"B' U2 B U B' U F B R' F' r U R U' r'",pattern:"UFUFLFLBRURURUBUUULUB"},
  {id:"ZBLL-H-16",name:"H 16",group:"H",cp:"4点循環",alg:"F U2 F2 U' F2 U' F2 U2 F2 U F' R' F U' F' U R",pattern:"UBUFFBLRLULURUBUUURUF"},
  {id:"ZBLL-H-17",name:"H 17",group:"H",cp:"4点循環",alg:"L U L' U L U2 R L' U2 R' U' R U' R' L U' R' U L' U' R",pattern:"UBUFRBLLLUFURUBUUURUF"},
  {id:"ZBLL-H-18",name:"H 18",group:"H",cp:"4点循環",alg:"L' U2 L U L' U R' L U L U' R U L' F U F' U F U2 F'",pattern:"RFBURUUBURLFFULUUUBUL"},
  {id:"ZBLL-H-19",name:"H 19",group:"H",cp:"4点循環",alg:"B' U' B U' B' U2 B R U2 R' U' R U' R' L U' R' U L' U' R",pattern:"RFBULUURURBFFULUUUBUL"},
  {id:"ZBLL-H-20",name:"H 20",group:"H",cp:"4点循環",alg:"B' U2 B U B' U F' B U' F U' F' U2 F L U' R' U L' U' R",pattern:"UFUFLBLRLUBURUBUUURUF"},
  {id:"ZBLL-H-21",name:"H 21",group:"H",cp:"4点循環",alg:"r U R' U' r' F R F' U' F R' F' r U R U' r'",pattern:"ULUFFBLBLURURUBUUURUF"},
  {id:"ZBLL-H-22",name:"H 22",group:"H",cp:"4点循環",alg:"L U2 L' U' L U' R L' U' L' U R' U' L B' U' B U' B' U2 B",pattern:"RLBURUUFURBFFULUUUBUL"},
  {id:"ZBLL-H-23",name:"H 23",group:"H",cp:"対角2点交換",alg:"F R' F' R U R U' R' F R U' R' U R U R' F' R U R' U R U' R' U R U2 R'",pattern:"RBRURUULULFLFUBUUUFUB"},
  {id:"ZBLL-H-24",name:"H 24",group:"H",cp:"対角2点交換",alg:"R' F' r U R U' r' F R U2 R' U' R U' R2 U L U' R U L'",pattern:"RFRURUUBULLLFUBUUUFUB"},
  {id:"ZBLL-H-25",name:"H 25",group:"H",cp:"対角2点交換",alg:"U2 M U2 M2 U2 M U' M2 U' M2 U R' U L U' R U R' L' U L U' R U L'",pattern:"UFUFLFBRBUBURURUUULUL"},
  {id:"ZBLL-H-26",name:"H 26",group:"H",cp:"対角2点交換",alg:"L U' R' U L' U' R F' U2 F U F' U r U R' U' r' F R",pattern:"UFUFBFBLBURURURUUULUL"},
  {id:"ZBLL-H-27",name:"H 27",group:"H",cp:"対角2点交換",alg:"R' F' r U R U' r' U' F U' F' U2 F R' U L U' R U L'",pattern:"RLRURUUFULBLFUBUUUFUB"},
  {id:"ZBLL-H-28",name:"H 28",group:"H",cp:"3点交換",alg:"R2 D' R U2 R' D R U2 R F R' F' r U R U' r'",pattern:"UBUFLLBRLUFURURUUUBUF"},
  {id:"ZBLL-H-29",name:"H 29",group:"H",cp:"3点交換",alg:"L' U' L U' L' U2 R' L F' r U R U' r' U2 F U F' U F",pattern:"URUFLLBFLUBURURUUUBUF"},
  {id:"ZBLL-H-30",name:"H 30",group:"H",cp:"4点循環",alg:"R' U2 R2 U R2 U R2 U2 R2 U' R F R' U R U' F'",pattern:"RRLULUUBUBFBFUFUUULUR"},
  {id:"ZBLL-H-31",name:"H 31",group:"H",cp:"4点循環",alg:"F R' F' r U R U' R r' U' L' U R' U' R' L F' r U R U' r' F",pattern:"ULULFRLBRURUFUBUUUFUB"},
  {id:"ZBLL-H-32",name:"H 32",group:"H",cp:"3点交換",alg:"R' F' r U R U' r' U2 F2 U F2 U F2 U2 F'",pattern:"FRBUBUULURFRLULUUUBUF"},
  {id:"ZBLL-H-33",name:"H 33",group:"H",cp:"3点交換",alg:"R' U2 R' D' R U2 R' D R2 U L U' R' U L' U' R",pattern:"FBRULUURUFFLLUBUUURUB"},
  {id:"ZBLL-H-34",name:"H 34",group:"H",cp:"3点交換",alg:"F R' F' r U R U' r' L' U2 L U L' U L",pattern:"ULULRRBBBUFUFURUUUFUL"},
  {id:"ZBLL-H-35",name:"H 35",group:"H",cp:"隣接2点交換",alg:"B' U2 B U B' U B L U' R' U L' U' R",pattern:"FRRUFUULUBBRLUBUUULUF"},
  {id:"ZBLL-H-36",name:"H 36",group:"H",cp:"隣接2点交換",alg:"L' U' L U' L' U' R U' L U R'",pattern:"FFRURUUBUBLRLUBUUULUF"},
  {id:"ZBLL-H-37",name:"H 37",group:"H",cp:"隣接2点交換",alg:"L U L' U L U R' U L' U' R",pattern:"FLRURUUFUBBRLUBUUULUF"},
  {id:"ZBLL-H-38",name:"H 38",group:"H",cp:"2組交換",alg:"M2 U' M2 U2 M2 U' R' M2 U L U' R U R' L' U L U' R U L'",pattern:"FBFULUURUBFBLURUUULUR"},
  {id:"ZBLL-H-39",name:"H 39",group:"H",cp:"2組交換",alg:"F U F' R' F U' F' U' R U R' U R2 U' L' U R' U' L",pattern:"UFULLLRBRURUFUFUUUBUB"},
  {id:"ZBLL-H-40",name:"H 40",group:"H",cp:"2組交換",alg:"R' U L U' R U R' L' U L U' R U L'",pattern:"FFFURUULUBBBLURUUULUR"},
  {id:"ZBLL-Pi-01",name:"Pi 01",group:"Pi",cp:"CP解決",alg:"B' U2 B U B' U B R' U2 R U R' U R",pattern:"URRBFFUBUULRLUBUUULUF"},
  {id:"ZBLL-Pi-02",name:"Pi 02",group:"Pi",cp:"CP解決",alg:"B U B' U B U2 B' R U R' U R U2 R'",pattern:"LRRUFFUBFULUBUBUUULUR"},
  {id:"ZBLL-Pi-03",name:"Pi 03",group:"Pi",cp:"CP解決",alg:"B' U' B U' B' U2 B2 U2 B' U' B U' B'",pattern:"URRBBFULUUFRLUBUUULUF"},
  {id:"ZBLL-Pi-04",name:"Pi 04",group:"Pi",cp:"CP解決",alg:"R' U' F U F' R U F U2 F' L U' R' U L' U' R",pattern:"UFRBBFURUULRLUBUUULUF"},
  {id:"ZBLL-Pi-05",name:"Pi 05",group:"Pi",cp:"CP解決",alg:"L U' R' U L' U' R2 U' L' U R' U' L",pattern:"LFRURFULFUBUBUBUUULUR"},
  {id:"ZBLL-Pi-06",name:"Pi 06",group:"Pi",cp:"CP解決",alg:"F' U2 F U F' U F2 U F' U F U2 F'",pattern:"LLUURUBBFLFUBURUUUFUR"},
  {id:"ZBLL-Pi-07",name:"Pi 07",group:"Pi",cp:"隣接2点交換",alg:"R' U2 R U F R' U R U' F' B' U2 B U B' U B",pattern:"LLRUBRURLUFUBUBUUUFUF"},
  {id:"ZBLL-Pi-08",name:"Pi 08",group:"Pi",cp:"隣接2点交換",alg:"R' F' r U R U' r' F2 U R' U' R F' R' U R",pattern:"LRUUBURFRLLUBUFUUUFUB"},
  {id:"ZBLL-Pi-09",name:"Pi 09",group:"Pi",cp:"隣接2点交換",alg:"L' U R U' L U R' B U2 B' U' B U' B'",pattern:"URUBFURLULBBLUFUUUFUR"},
  {id:"ZBLL-Pi-10",name:"Pi 10",group:"Pi",cp:"隣接2点交換",alg:"L U' R' U L' U' R2 U R' U R U2 R'",pattern:"LRFUFFULRUBUBURUUULUB"},
  {id:"ZBLL-Pi-11",name:"Pi 11",group:"Pi",cp:"隣接2点交換",alg:"B U B' U B U2 B' R U' L' U R' U' L",pattern:"LFFURFUBRULUBURUUULUB"},
  {id:"ZBLL-Pi-12",name:"Pi 12",group:"Pi",cp:"隣接2点交換",alg:"L U' R' U L' U R U R' U R",pattern:"UFFBRFUBUULBLURUUULUR"},
  {id:"ZBLL-Pi-13",name:"Pi 13",group:"Pi",cp:"隣接2点交換",alg:"B' U' B U' B' U2 B R' U L U' R U L'",pattern:"UFFBBFULUURBLURUUULUR"},
  {id:"ZBLL-Pi-14",name:"Pi 14",group:"Pi",cp:"隣接2点交換",alg:"L' U R U' L U R2 U' R U' R' U2 R",pattern:"UFUBBURLULRBLUFUUUFUR"},
  {id:"ZBLL-Pi-15",name:"Pi 15",group:"Pi",cp:"隣接2点交換",alg:"L U' R' U L' U' R F' U2 F U F' U F",pattern:"LFFUBFULRURUBURUUULUB"},
  {id:"ZBLL-Pi-16",name:"Pi 16",group:"Pi",cp:"隣接2点交換",alg:"L' U R U' L U' R' U' R U' R'",pattern:"ULFBRFUFUUBBLURUUULUR"},
  {id:"ZBLL-Pi-17",name:"Pi 17",group:"Pi",cp:"3点交換",alg:"R U R' U R U2 R2 F' r U R U' r' F",pattern:"LLLURRUBRUFUBUFUUUFUB"},
  {id:"ZBLL-Pi-18",name:"Pi 18",group:"Pi",cp:"対角2点交換",alg:"F R' F' R U R U' R' F R U' R' U R U R' F2 U2 F2 U F2 U F2 U2 F'",pattern:"LBUURUFLFRFUBULUUUBUR"},
  {id:"ZBLL-Pi-19",name:"Pi 19",group:"Pi",cp:"対角2点交換",alg:"R' F' r U R U' r' F U R' U2 R' D' R U2 R' D R2",pattern:"LRUUBUFFFRLUBULUUUBUR"},
  {id:"ZBLL-Pi-20",name:"Pi 20",group:"Pi",cp:"対角2点交換",alg:"F R' F' R U R U' R' F R U' R' U R U R' F' R U2 R2 U' R2 U' R2 U2 R",pattern:"UFUBLUFRURBRLULUUUBUF"},
  {id:"ZBLL-Pi-21",name:"Pi 21",group:"Pi",cp:"対角2点交換",alg:"L U L' U L U R' U L' U' R F R' F' r U R U' r'",pattern:"ULUBRUFFURBRLULUUUBUF"},
  {id:"ZBLL-Pi-22",name:"Pi 22",group:"Pi",cp:"隣接2点交換",alg:"L' U R U' L U R' U L' U R U' L U R'",pattern:"ULBRFFUBUURRBULUUULUF"},
  {id:"ZBLL-Pi-23",name:"Pi 23",group:"Pi",cp:"2組交換",alg:"R' U' R U' R' U2 R2 U' L' U R' U' R' L U L U' R U L'",pattern:"UBBRRRUFUULFBULUUUFUL"},
  {id:"ZBLL-Pi-24",name:"Pi 24",group:"Pi",cp:"2組交換",alg:"L U' R' U L' U' R L' U' L U' L' U2 R' L U L U' R U L'",pattern:"URBRLRUFUUBFBULUUUFUL"},
  {id:"ZBLL-Pi-25",name:"Pi 25",group:"Pi",cp:"2組交換",alg:"B' U2 B U B' U B R U' L' U R' U' R' L U L U' R U L'",pattern:"BFUULULBLFRURUBUUURUF"},
  {id:"ZBLL-Pi-26",name:"Pi 26",group:"Pi",cp:"2組交換",alg:"B U2 B' U' B U' B' R U' L' U R' U' R' L U L U' R U L'",pattern:"UFBRBRURUULFBULUUUFUL"},
  {id:"ZBLL-Pi-27",name:"Pi 27",group:"Pi",cp:"2組交換",alg:"R U R' U R U2 R2 U L U' R U R L' U' L' U R' U' L",pattern:"ULBRRRUBUUFFBULUUUFUL"},
  {id:"ZBLL-Pi-28",name:"Pi 28",group:"Pi",cp:"2組交換",alg:"L U' R' U L' U' R L' U R U' L U R' B U B' U B U2 B'",pattern:"BLUUFULRLFBURUBUUURUF"},
  {id:"ZBLL-Pi-29",name:"Pi 29",group:"Pi",cp:"3点交換",alg:"r U R' U' r' F R F' B' U' B U' B' U2 B",pattern:"URURLURFULBLBUFUUUFUB"},
  {id:"ZBLL-Pi-30",name:"Pi 30",group:"Pi",cp:"3点交換",alg:"r U R' U' r' F R F' R' U2 R2 U R2 U R2 U2 R'",pattern:"BFUUBURRBLLURUFUUUFUL"},
  {id:"ZBLL-Pi-31",name:"Pi 31",group:"Pi",cp:"4点循環",alg:"r U R' U' r' F R F' U F R' F' r U R U' r'",pattern:"URLRBRUFUULLBUFUUUFUB"},
  {id:"ZBLL-Pi-32",name:"Pi 32",group:"Pi",cp:"4点循環",alg:"B U2 B' U' B U' B' L' U R U' L U R' L U L' U L U2 L'",pattern:"UFLRLRURUUBLBUFUUUFUB"},
  {id:"ZBLL-Pi-33",name:"Pi 33",group:"Pi",cp:"4点循環",alg:"B U2 B' U' B U' B2 U2 B U B' U B R' U L U' R U L'",pattern:"UFURLUFRUFBLBULUUURUB"},
  {id:"ZBLL-Pi-34",name:"Pi 34",group:"Pi",cp:"4点循環",alg:"F U F' R' F U' F' U R2 U2 R' U' R U' R'",pattern:"ULLRRRUFUUBLBUFUUUFUB"},
  {id:"ZBLL-Pi-35",name:"Pi 35",group:"Pi",cp:"3点交換",alg:"F R' F' r U R U' R r' U R' U R U' R' U R U2 R'",pattern:"URURBUFLUBFRBULUUULUF"},
  {id:"ZBLL-Pi-36",name:"Pi 36",group:"Pi",cp:"3点交換",alg:"R' U' R U' R' U2 R F U F' U F U2 R' F' r U R U' r'",pattern:"UFLRBLURUULRBUFUUUBUF"},
  {id:"ZBLL-Pi-37",name:"Pi 37",group:"Pi",cp:"3点交換",alg:"F R' F' r U R U' r' F' U2 F U F' U' F U F' U F",pattern:"UFURBUFRUBLRBULUUULUF"},
  {id:"ZBLL-Pi-38",name:"Pi 38",group:"Pi",cp:"3点交換",alg:"F U2 F2 U' F2 U' F2 U2 r U R' U' r' F R",pattern:"BLUURUFBFBFURULUUULUR"},
  {id:"ZBLL-Pi-39",name:"Pi 39",group:"Pi",cp:"3点交換",alg:"F' U2 F2 U F2 U F2 U2 R' F' r U R U' r'",pattern:"URBFBFULUUFBRULUUULUR"},
  {id:"ZBLL-Pi-40",name:"Pi 40",group:"Pi",cp:"3点交換",alg:"L U L' U L U2 L' F' U' F U' F' U2 r U R' U' r' F R",pattern:"RFUULULBRLRUFUBUUUFUB"},
  {id:"ZBLL-Pi-41",name:"Pi 41",group:"Pi",cp:"3点交換",alg:"R U2 R2 U' R2 U' R2 U2 R F R' F' r U R U' r'",pattern:"RLBUFFURRUBUFULUUULUB"},
  {id:"ZBLL-Pi-42",name:"Pi 42",group:"Pi",cp:"4点循環",alg:"L U L' U L U2 L2 U' L U' L' U2 L2 U' R' U L' U' R",pattern:"RBUURULLLRFUFUBUUUBUF"},
  {id:"ZBLL-Pi-43",name:"Pi 43",group:"Pi",cp:"4点循環",alg:"F U2 F' U' F U' F2 U2 F U F' U F L U' R' U L' U' R",pattern:"UBUFRULLURFFRUBUUUBUL"},
  {id:"ZBLL-Pi-44",name:"Pi 44",group:"Pi",cp:"4点循環",alg:"B' U2 B U B' U B2 U2 B' U' B U' B' L' U R U' L U R'",pattern:"RBBURBULLUFUFULUUURUF"},
  {id:"ZBLL-Pi-45",name:"Pi 45",group:"Pi",cp:"4点循環",alg:"L U' R' U L' U' R L' U' L U' L' U2 L B U2 B' U' B U' B'",pattern:"UFBFLBURUUBFRULUUURUL"},
  {id:"ZBLL-Pi-46",name:"Pi 46",group:"Pi",cp:"4点循環",alg:"B' U2 B U B' U B2 U2 B' U' B U' B' L U' R' U L' U' R",pattern:"UFUFLULRURBFRUBUUUBUL"},
  {id:"ZBLL-Pi-47",name:"Pi 47",group:"Pi",cp:"4点循環",alg:"U R U' L' U R' U' L2 U' R' U L' U R' D' R U2 R' D R2",pattern:"RLBUFBUBLURUFULUUURUF"},
  {id:"ZBLL-Pi-48",name:"Pi 48",group:"Pi",cp:"対角2点交換",alg:"F U R' U' R F' R' U F' r U R U' r' F",pattern:"RRUUBUBFBLLUFURUUUFUL"},
  {id:"ZBLL-Pi-49",name:"Pi 49",group:"Pi",cp:"対角2点交換",alg:"R' U' R U' R' U' L U' R U L' F' r U R' U' r' F R",pattern:"URUFFUBLULBLRURUUUFUB"},
  {id:"ZBLL-Pi-50",name:"Pi 50",group:"Pi",cp:"2組交換",alg:"F' U2 F U F' U F2 U2 F' U' F U' F' R U R' U R U2 R'",pattern:"RRLULBUFBUBUFUFUUURUL"},
  {id:"ZBLL-Pi-51",name:"Pi 51",group:"Pi",cp:"2組交換",alg:"B U2 B' U' B U' B2 U2 B U B' U B2 U2 B' U' B U' B'",pattern:"URUFLUFFURBLRULUUUBUB"},
  {id:"ZBLL-Pi-52",name:"Pi 52",group:"Pi",cp:"2組交換",alg:"F' U2 F2 U F2 U F2 U2 F'",pattern:"URUFBUFLURFLRULUUUBUB"},
  {id:"ZBLL-Pi-53",name:"Pi 53",group:"Pi",cp:"2組交換",alg:"F' U2 F U F' U F2 U2 F' U' F U' F2 U2 F U F' U F",pattern:"RFLULBUBBURUFUFUUURUL"},
  {id:"ZBLL-Pi-54",name:"Pi 54",group:"Pi",cp:"2組交換",alg:"R U2 R2 U' R2 U' R2 U2 R2 U' R U R U R U' R' U' R2",pattern:"RFUURUFLBRBUFULUUUBUL"},
  {id:"ZBLL-Pi-55",name:"Pi 55",group:"Pi",cp:"2組交換",alg:"F U2 F2 U' F2 U' F2 U2 F",pattern:"ULUFRUFBURFLRULUUUBUB"},
  {id:"ZBLL-Pi-56",name:"Pi 56",group:"Pi",cp:"4点循環",alg:"R' F' r U R U' r' F U' F U2 F2 U' F2 U' F2 U2 F",pattern:"URLFFLULUUBBRUFUUUBUR"},
  {id:"ZBLL-Pi-57",name:"Pi 57",group:"Pi",cp:"4点循環",alg:"L U' R' U L' U' R U R U' L' U R' U' L",pattern:"ULLFFLUBUURBRUFUUUBUR"},
  {id:"ZBLL-Pi-58",name:"Pi 58",group:"Pi",cp:"3点交換",alg:"L' U R U' L U R' U R2 D' R U2 R' D R U2 R",pattern:"FFBURBULFUBULULUUURUR"},
  {id:"ZBLL-Pi-59",name:"Pi 59",group:"Pi",cp:"3点交換",alg:"R U2 R' U' R U R' U' R U' R' r U R' U' r' F R F'",pattern:"FLUURULBFRFULUBUUUBUR"},
  {id:"ZBLL-Pi-60",name:"Pi 60",group:"Pi",cp:"3点交換",alg:"R' F' r U R U' r' F B U B' U B U2 B'",pattern:"ULULFULRURBRFUBUUUBUF"},
  {id:"ZBLL-Pi-61",name:"Pi 61",group:"Pi",cp:"3点交換",alg:"F' U' F U' F' U F U' F' U2 F r U R' U' r' F R F'",pattern:"FLUUFULRFRBULUBUUUBUR"},
  {id:"ZBLL-Pi-62",name:"Pi 62",group:"Pi",cp:"3点交換",alg:"r U R' U' r' F R F' R' U2 R' D' R U2 R' D R2",pattern:"UBRLLRURUUFLFUBUUUFUB"},
  {id:"ZBLL-Pi-63",name:"Pi 63",group:"Pi",cp:"3点交換",alg:"F' U' F U' F' U2 r U R' U' r' F R F U F' U F U2 F'",pattern:"URRLFRUBUULLFUBUUUFUB"},
  {id:"ZBLL-Pi-64",name:"Pi 64",group:"Pi",cp:"3点交換",alg:"F' U' F U' F' U2 r U R' U' r' F R L' U2 L U L' U L",pattern:"UFRLLRUBUURLFUBUUUFUB"},
  {id:"ZBLL-Pi-65",name:"Pi 65",group:"Pi",cp:"3点交換",alg:"F R' F' r U R U' R' r' U2 R2 U R2 U R2 U2 R'",pattern:"FFUUBUBRBFLULURUUURUL"},
  {id:"ZBLL-Pi-66",name:"Pi 66",group:"Pi",cp:"隣接2点交換",alg:"L U2 L' U' L U' L2 U R U' L U R'",pattern:"FRRUFLULFUBULUBUUUBUR"},
  {id:"ZBLL-Pi-67",name:"Pi 67",group:"Pi",cp:"隣接2点交換",alg:"B U B' U B U2 B' L U' R' U L' U' R",pattern:"FFUURUBBFBLULURUUULUR"},
  {id:"ZBLL-Pi-68",name:"Pi 68",group:"Pi",cp:"隣接2点交換",alg:"B' U' B U' B' U2 B L' U R U' L U R'",pattern:"FFRUBLULFURULUBUUUBUR"},
  {id:"ZBLL-Pi-69",name:"Pi 69",group:"Pi",cp:"隣接2点交換",alg:"L' U2 L U L' U L2 U' R' U L' U' R",pattern:"UFULBUBLUBRRFURUUULUF"},
  {id:"ZBLL-Pi-70",name:"Pi 70",group:"Pi",cp:"4点循環",alg:"F U R' U' R F' R' U R2 U2 R2 U' R2 U' R2 U2 R",pattern:"FRFULBUBBUFULURUUURUL"},
  {id:"ZBLL-Pi-71",name:"Pi 71",group:"Pi",cp:"4点循環",alg:"r U R' U' r' F R U R' U' R F' R' U F' r U R U' r' F",pattern:"FRUUBURFBRLULUFUUUBUL"},
  {id:"ZBLL-Pi-72",name:"Pi 72",group:"Pi",cp:"4点循環",alg:"F' U2 F2 U F2 U F2 U2 F' U F' r U R' U' r' F R",pattern:"UFFLRBUBUULLFURUUURUB"},
  {id:"ZBLL-Sune-01",name:"Sune 01",group:"Sune",cp:"CP解決",alg:"F U2 F2 U' F2 U' F2 U2 F R U2 R' U' R U' R'",pattern:"BBRLLUURFLFUUUBUUUFUR"},
  {id:"ZBLL-Sune-02",name:"Sune 02",group:"Sune",cp:"CP解決",alg:"B U2 B' U' B U' B' L' U' L U' L' U2 L",pattern:"BFRLRUULFLBUUUBUUUFUR"},
  {id:"ZBLL-Sune-03",name:"Sune 03",group:"Sune",cp:"CP解決",alg:"B' U' B U' B' U2 B R U2 R' U' R U' R'",pattern:"ULRBBLUFFFRULUBUUUUUR"},
  {id:"ZBLL-Sune-04",name:"Sune 04",group:"Sune",cp:"隣接2点交換",alg:"x R2 D2 R U R' D2 R U' x' R2 U' L' U R' U' L",pattern:"ULRBFFUBLRRULUBUUUUUF"},
  {id:"ZBLL-Sune-05",name:"Sune 05",group:"Sune",cp:"隣接2点交換",alg:"L U' R' U L' U' x U R' D2 R U' R' D2 x' R2",pattern:"ULBBFURBLFRULUUUUURUF"},
  {id:"ZBLL-Sune-06",name:"Sune 06",group:"Sune",cp:"隣接2点交換",alg:"L U' R' U L' U R' D' R U2 R' D R2",pattern:"BLRLFUUBLFRUUUBUUURUF"},
  {id:"ZBLL-Sune-07",name:"Sune 07",group:"Sune",cp:"隣接2点交換",alg:"L' U R U' L U R2 U2 R2 U R2 U R2 U2 R'",pattern:"BRFLFUULRLBUUURUUUFUB"},
  {id:"ZBLL-Sune-08",name:"Sune 08",group:"Sune",cp:"隣接2点交換",alg:"L' U' L U' L' U2 R' L U L U' R U L'",pattern:"UFFBRUUBBLLRLURUUUFUU"},
  {id:"ZBLL-Sune-09",name:"Sune 09",group:"Sune",cp:"3点交換",alg:"R2 D' R U2 R' D R2 U R' U R",pattern:"UBRBFUFLLRRULUUUUUBUF"},
  {id:"ZBLL-Sune-10",name:"Sune 10",group:"Sune",cp:"3点交換",alg:"x R2 D2 R U R' D2 R U' x' R B' U2 B U B' U B",pattern:"UFFBLUUBFRRLLURUUUBUU"},
  {id:"ZBLL-Sune-11",name:"Sune 11",group:"Sune",cp:"3点交換",alg:"F U F' U F U2 F' R' F' r U R U' r' F",pattern:"UFLBLFUBRRRULUFUUUUUB"},
  {id:"ZBLL-Sune-12",name:"Sune 12",group:"Sune",cp:"3点交換",alg:"B' U2 B U B' U B x R' U R' D2 R U' R' D2 x' R2",pattern:"UFFBLULBRFRULUUUUURUB"},
  {id:"ZBLL-Sune-13",name:"Sune 13",group:"Sune",cp:"3点交換",alg:"B U B' U B U2 B' R' U2 R' D' R U2 R' D R2",pattern:"BLLLFUURRFBUUUFUUURUB"},
  {id:"ZBLL-Sune-14",name:"Sune 14",group:"Sune",cp:"対角2点交換",alg:"R U' L' U R' U L U L' U2 R U' L U R' U'",pattern:"URLBFRULFBBULUFUUUUUR"},
  {id:"ZBLL-Sune-15",name:"Sune 15",group:"Sune",cp:"対角2点交換",alg:"R U' L' U R' U' L F' r U R' U' r' F R",pattern:"ULLBFUUBRRRFLUFUUUBUU"},
  {id:"ZBLL-Sune-16",name:"Sune 16",group:"Sune",cp:"隣接2点交換",alg:"F' r U R' U' r' F R U r U R' U' r' F R F'",pattern:"URLRBUBFFLLUBUUUUUFUR"},
  {id:"ZBLL-Sune-17",name:"Sune 17",group:"Sune",cp:"2組交換",alg:"x U2 r' U' r U2 R' F R' F' x' R' U' L' U R' U' L",pattern:"UBBRFFULLRRUBULUUUUUF"},
  {id:"ZBLL-Sune-18",name:"Sune 18",group:"Sune",cp:"2組交換",alg:"L U' R' U L' U' R F R U' R' U R U R2 F' R U R U' R'",pattern:"URLRFUBBLFLUBUUUUURUF"},
  {id:"ZBLL-Sune-19",name:"Sune 19",group:"Sune",cp:"2組交換",alg:"D' R U R' U' D R2 U' R U' R' U R' U R' U' L' U R' U' L",pattern:"URBRBFULLRFUBULUUUUUF"},
  {id:"ZBLL-Sune-20",name:"Sune 20",group:"Sune",cp:"2組交換",alg:"F' r U R' U' r' F R2 U2 R' U' R U' R2 F' r U R U' r' F",pattern:"URLRBUBLLFFUBUUUUURUF"},
  {id:"ZBLL-Sune-21",name:"Sune 21",group:"Sune",cp:"2組交換",alg:"D R' U' R U D' R2 U R' U R U' R U' R' U' L' U R' U' L",pattern:"UFBRBFURLRLUBULUUUUUF"},
  {id:"ZBLL-Sune-22",name:"Sune 22",group:"Sune",cp:"2組交換",alg:"L' U R U' L U R2 U' R U' R' U' L U' R U L'",pattern:"ULBRRFUBLRFUBULUUUUUF"},
  {id:"ZBLL-Sune-23",name:"Sune 23",group:"Sune",cp:"2組交換",alg:"U R U R2 F' R U R U' R' F R U2 L' U R' U' L",pattern:"ULBRFFURLRBUBULUUUUUF"},
  {id:"ZBLL-Sune-24",name:"Sune 24",group:"Sune",cp:"2組交換",alg:"F R U' R' U R U R2 F' R U R U2 L' U R' U' L",pattern:"ULBRBFUFLRRUBULUUUUUF"},
  {id:"ZBLL-Sune-25",name:"Sune 25",group:"Sune",cp:"3点交換",alg:"U' L' U2 L U L' U L2 U2 L' U' L U2 R' U L' U' R",pattern:"URRRFUFBBLLUBUUUUUFUL"},
  {id:"ZBLL-Sune-26",name:"Sune 26",group:"Sune",cp:"3点交換",alg:"r U R' U' r' F R F2 U2 F U F' U F",pattern:"ULFRFLURBFBUBURUUUUUL"},
  {id:"ZBLL-Sune-27",name:"Sune 27",group:"Sune",cp:"4点循環",alg:"L U L' U L U R' U L' U' R F' U' F U' F' U2 F",pattern:"UBLRRFULBRFUBUFUUUUUL"},
  {id:"ZBLL-Sune-28",name:"Sune 28",group:"Sune",cp:"4点循環",alg:"B' U' B U' B' U2 B2 U B' U B U2 B' R U' L' U R' U' L",pattern:"RBLBRUULBFFUUUFUUURUL"},
  {id:"ZBLL-Sune-29",name:"Sune 29",group:"Sune",cp:"4点循環",alg:"R U' L' U R' U' R2 L U R U R' U' R' U' R' U R'",pattern:"URLRLFUBBRFUBUFUUUUUL"},
  {id:"ZBLL-Sune-30",name:"Sune 30",group:"Sune",cp:"4点循環",alg:"F U F' U F U2 R U' R' U R U R2 F' R U R U' R'",pattern:"RFLBRUUBBFLUUUFUUURUL"},
  {id:"ZBLL-Sune-31",name:"Sune 31",group:"Sune",cp:"4点循環",alg:"L U2 L' U' L U' L' B' U' B U' B' U2 B R' U L U' R U L'",pattern:"UFLRLUURLFBBBUFUUURUU"},
  {id:"ZBLL-Sune-32",name:"Sune 32",group:"Sune",cp:"4点循環",alg:"B' U2 B U B' U B x U2 r' U' r U2 R' F R' F' x' R2",pattern:"UFFRLULRBFBUBUUUUURUL"},
  {id:"ZBLL-Sune-33",name:"Sune 33",group:"Sune",cp:"4点循環",alg:"F U F' U F U2 F' x U2 r' U' r U2 R' F R' F' x' R2",pattern:"RFLBLUURBFBUUUFUUURUL"},
  {id:"ZBLL-Sune-34",name:"Sune 34",group:"Sune",cp:"4点循環",alg:"R2 U R U R' U' R' U' R' L' U R' U' L",pattern:"ULLRBFURBRFUBUFUUUUUL"},
  {id:"ZBLL-Sune-35",name:"Sune 35",group:"Sune",cp:"4点循環",alg:"R' U' F U F' R U F U2 F'",pattern:"ULFRRULFBFBUBUUUUURUL"},
  {id:"ZBLL-Sune-36",name:"Sune 36",group:"Sune",cp:"4点循環",alg:"R U' L' U R' U' L2 U L' U L U2 L' B U2 B' U' B U' B'",pattern:"RLLBRUUFBFBUUUFUUURUL"},
  {id:"ZBLL-Sune-37",name:"Sune 37",group:"Sune",cp:"3点交換",alg:"R' U2 R U R' U R' D' R U2 R' D R U2 R",pattern:"UBLRFBULFLRUBUFUUUUUR"},
  {id:"ZBLL-Sune-38",name:"Sune 38",group:"Sune",cp:"3点交換",alg:"F U F' U F U2 F2 r U R' U' r' F R",pattern:"UFLRLUUBRBRFBUFUUULUU"},
  {id:"ZBLL-Sune-39",name:"Sune 39",group:"Sune",cp:"3点交換",alg:"B U B' U B U2 B' R2 D' R U2 R' D R U2 R",pattern:"ULLRFBURFLBUBUFUUUUUR"},
  {id:"ZBLL-Sune-40",name:"Sune 40",group:"Sune",cp:"3点交換",alg:"U R' U2 R U R' U' R' D' R U2 R' D R2 U'",pattern:"UFBFLLUBRFRURULUUUUUB"},
  {id:"ZBLL-Sune-41",name:"Sune 41",group:"Sune",cp:"3点交換",alg:"R U R' U R U2 R' F R' F' r U R U' r'",pattern:"ULLFRUBBRLFURUUUUUFUB"},
  {id:"ZBLL-Sune-42",name:"Sune 42",group:"Sune",cp:"3点交換",alg:"F' U2 F U F' U F2 R' F' r U R U' r'",pattern:"ULLFFUBRRLBURUUUUUFUB"},
  {id:"ZBLL-Sune-43",name:"Sune 43",group:"Sune",cp:"4点循環",alg:"R U2 R' U' R U R' U' R U' R' L' U R U' L U R'",pattern:"FBBRFUURLRLUUULUUUBUF"},
  {id:"ZBLL-Sune-44",name:"Sune 44",group:"Sune",cp:"4点循環",alg:"x U2 r' U' r U2 R' F R' F' x' R' U R' U R U2 R'",pattern:"UBBFRRULLBFURULUUUUUF"},
  {id:"ZBLL-Sune-45",name:"Sune 45",group:"Sune",cp:"4点循環",alg:"L U2 L' U' L U L' U' L U' L2 U R U' L U R'",pattern:"FRBRLUUBLRFUUULUUUBUF"},
  {id:"ZBLL-Sune-46",name:"Sune 46",group:"Sune",cp:"4点循環",alg:"L U' R' U L' U' R' U R U R' U' R' U' R' U R'",pattern:"URLFLUBBLRFURUUUUUBUF"},
  {id:"ZBLL-Sune-47",name:"Sune 47",group:"Sune",cp:"4点循環",alg:"M2 U' M2 U2 M2 U' M2 L U' R' U L' U' R",pattern:"URLFBUBFLRLURUUUUUBUF"},
  {id:"ZBLL-Sune-48",name:"Sune 48",group:"Sune",cp:"4点循環",alg:"U2 M U2 M2 U2 M U' M2 U' M2 L U' R' U L' U' R",pattern:"UFLFLUBRLRBURUUUUUBUF"},
  {id:"ZBLL-Sune-49",name:"Sune 49",group:"Sune",cp:"4点循環",alg:"L U' R' U L' U' R",pattern:"ULLFFUBBLRRURUUUUUBUF"},
  {id:"ZBLL-Sune-50",name:"Sune 50",group:"Sune",cp:"4点循環",alg:"F R U' R' U R U R2 F' R U2 R U2 R'",pattern:"ULBFBRURLBFURULUUUUUF"},
  {id:"ZBLL-Sune-51",name:"Sune 51",group:"Sune",cp:"対角2点交換",alg:"F U F' U F U' R' U' R F' R' U R r U R' U' r' F R F'",pattern:"FLRRBUURBLFUUUBUUUFUL"},
  {id:"ZBLL-Sune-52",name:"Sune 52",group:"Sune",cp:"3点交換",alg:"L U' R' U L' U2 R F R' U R U' F'",pattern:"UFRFRUULFBBLRUBUUULUU"},
  {id:"ZBLL-Sune-53",name:"Sune 53",group:"Sune",cp:"2組交換",alg:"F' U2 F U F' U F M2 U' M2 U2 M2 U' M2",pattern:"URLFBRULBBFURUFUUUUUL"},
  {id:"ZBLL-Sune-54",name:"Sune 54",group:"Sune",cp:"2組交換",alg:"M2 U' M2 U2 M2 U' M2 B' U2 B U B' U B",pattern:"URFFBULLBRFURUUUUUBUL"},
  {id:"ZBLL-Sune-55",name:"Sune 55",group:"Sune",cp:"2組交換",alg:"B U B' U B U2 B' M2 U' M2 U2 M2 U' M2",pattern:"URLFBUULLRFBRUFUUUBUU"},
  {id:"ZBLL-Sune-56",name:"Sune 56",group:"Sune",cp:"2組交換",alg:"M2 U' M2 U2 M2 U' M2 F U F' U F U2 F'",pattern:"FRLRBUULBRFUUUFUUUBUL"},
  {id:"ZBLL-Sune-57",name:"Sune 57",group:"Sune",cp:"2組交換",alg:"B' U2 B U B' U B",pattern:"UFFFLULBBRRURUUUUUBUL"},
  {id:"ZBLL-Sune-58",name:"Sune 58",group:"Sune",cp:"2組交換",alg:"B U2 B' U' B U' B' R U2 R' U' R U R' U' R U' R'",pattern:"UFLFLUUBLRRBRUFUUUBUU"},
  {id:"ZBLL-Sune-59",name:"Sune 59",group:"Sune",cp:"2組交換",alg:"R U R' U R U R U R U R U' R' U' R2",pattern:"UFLFLRUBBBRURUFUUUUUL"},
  {id:"ZBLL-Sune-60",name:"Sune 60",group:"Sune",cp:"2組交換",alg:"B U B' U B U2 B'",pattern:"ULLFFUURLRBBRUFUUUBUU"},
  {id:"ZBLL-Sune-61",name:"Sune 61",group:"Sune",cp:"2組交換",alg:"R2 U R U R' U' R' U' R' U2 R' U R U2 R'",pattern:"ULLFBRUFBBRURUFUUUUUL"},
  {id:"ZBLL-Sune-62",name:"Sune 62",group:"Sune",cp:"4点循環",alg:"R' U2 R U F R' U R U' F'",pattern:"ULFFRULFRBBURUUUUULUB"},
  {id:"ZBLL-Sune-63",name:"Sune 63",group:"Sune",cp:"3点交換",alg:"R' U2 R' D' R U2 R' D R2 L U L' U L U2 L'",pattern:"UBBLFUULRRRFFULUUUBUU"},
  {id:"ZBLL-Sune-64",name:"Sune 64",group:"Sune",cp:"3点交換",alg:"R' F' r U R U' r' F2 U F' U F U2 F'",pattern:"UFLLLUBBFRRUFUUUUUBUR"},
  {id:"ZBLL-Sune-65",name:"Sune 65",group:"Sune",cp:"3点交換",alg:"R' F' r U R U' r' F L' U2 L U L' U L",pattern:"ULLLRUBBFRFUFUUUUUBUR"},
  {id:"ZBLL-Sune-66",name:"Sune 66",group:"Sune",cp:"3点交換",alg:"x R' U R' D2 R U' R' D2 x' R' U R' U R U2 R'",pattern:"ULBLRRUBFBFUFULUUUUUR"},
  {id:"ZBLL-Sune-67",name:"Sune 67",group:"Sune",cp:"3点交換",alg:"F R' F' r U R U' r' F' U2 F U F' U F",pattern:"ULRLFFURBRBUFUBUUUUUL"},
  {id:"ZBLL-Sune-68",name:"Sune 68",group:"Sune",cp:"隣接2点交換",alg:"F U2 F2 U' F2 U' F2 U2 F L' U R U' L U R'",pattern:"UBRLFBURFLLUFUBUUUUUR"},
  {id:"ZBLL-Sune-69",name:"Sune 69",group:"Sune",cp:"隣接2点交換",alg:"F' U2 F2 U F2 U F2 U2 F' L' U R U' L U R'",pattern:"UFRLRBUBFLLUFUBUUUUUR"},
  {id:"ZBLL-Sune-70",name:"Sune 70",group:"Sune",cp:"隣接2点交換",alg:"B U2 B' U' B U' B' L' U R U' L U R'",pattern:"LLRFRUUFFBBUUUBUUULUR"},
  {id:"ZBLL-Sune-71",name:"Sune 71",group:"Sune",cp:"4点循環",alg:"F R' F' r U R U' R r' U' L' U R' U' L",pattern:"ULFLFRUBBBRUFURUUUUUL"},
  {id:"ZBLL-Sune-72",name:"Sune 72",group:"Sune",cp:"2組交換",alg:"r U R' U' r' F R F' R2 D' R U2 R' D R U2 R",pattern:"UBFLLUURBBFRFURUUULUU"},
  {id:"ZBLL-ASune-01",name:"Anti-Sune 01",group:"Anti-Sune",cp:"CP解決",alg:"R2 D' R U2 R' D R U2 F' r U R U' r' F",pattern:"LBUULLBRUFFRBURUUUUUF"},
  {id:"ZBLL-ASune-02",name:"Anti-Sune 02",group:"Anti-Sune",cp:"CP解決",alg:"B U B' U B U2 B' L' U2 L U L' U L",pattern:"LRUUFFBBRULFBURUUULUU"},
  {id:"ZBLL-ASune-03",name:"Anti-Sune 03",group:"Anti-Sune",cp:"CP解決",alg:"B' U2 B U B' U B R U R' U R U2 R'",pattern:"LFBURFRLUUBRBUUUUULUF"},
  {id:"ZBLL-ASune-04",name:"Anti-Sune 04",group:"Anti-Sune",cp:"隣接2点交換",alg:"R2 D' R U2 R' D R U' L U' R U L'",pattern:"BRULBRBFUULFUURUUUFUL"},
  {id:"ZBLL-ASune-05",name:"Anti-Sune 05",group:"Anti-Sune",cp:"隣接2点交換",alg:"x R2 D2 R U R' D2 R U' x' U L U' R U L'",pattern:"LRBUBRRFUULFBUUUUUFUL"},
  {id:"ZBLL-ASune-06",name:"Anti-Sune 06",group:"Anti-Sune",cp:"隣接2点交換",alg:"F R' F' r U R U' r' U R' U2 R' D' R U2 R' D R2",pattern:"LRUUBRBFFULLBURUUUFUU"},
  {id:"ZBLL-ASune-07",name:"Anti-Sune 07",group:"Anti-Sune",cp:"隣接2点交換",alg:"B' U2 B U B' U B R U' L' U R' U' L",pattern:"LRRUFFFLUUBBBUUUUULUR"},
  {id:"ZBLL-ASune-08",name:"Anti-Sune 08",group:"Anti-Sune",cp:"隣接2点交換",alg:"R U2 R2 U' R2 U' R2 U2 R2 U' L' U R' U' L",pattern:"BFULRFRBUULBUUFUUULUR"},
  {id:"ZBLL-ASune-09",name:"Anti-Sune 09",group:"Anti-Sune",cp:"隣接2点交換",alg:"F U2 F2 U' F2 U' F2 U2 F R U' L' U R' U' L",pattern:"LFUUBFRLBURRBUFUUULUU"},
  {id:"ZBLL-ASune-10",name:"Anti-Sune 10",group:"Anti-Sune",cp:"隣接2点交換",alg:"L U' R' U L' U' R2 U2 R2 U' R2 U' R2 U2 R",pattern:"LFUUBLRLUFRBBUFUUUUUR"},
  {id:"ZBLL-ASune-11",name:"Anti-Sune 11",group:"Anti-Sune",cp:"隣接2点交換",alg:"L U L' U L U2 R L' U' L' U R' U' L",pattern:"LLRURFFFUUBBBUUUUULUR"},
  {id:"ZBLL-ASune-12",name:"Anti-Sune 12",group:"Anti-Sune",cp:"3点交換",alg:"F' r U R' U' r' F R F U2 F' U' F U' F'",pattern:"LRUULBRFFUBLBUFUUURUU"},
  {id:"ZBLL-ASune-13",name:"Anti-Sune 13",group:"Anti-Sune",cp:"3点交換",alg:"R' U' R U' R2 D' R U2 R' D R2",pattern:"LBUURRFFBULRBULUUUFUU"},
  {id:"ZBLL-ASune-14",name:"Anti-Sune 14",group:"Anti-Sune",cp:"3点交換",alg:"L U2 L' U' L U' x R' L' U R' D2 R U' R' D2 x' R2",pattern:"LBUURFFFURLBBULUUUUUR"},
  {id:"ZBLL-ASune-15",name:"Anti-Sune 15",group:"Anti-Sune",cp:"3点交換",alg:"R' U' R U' R' U2 R U L U2 L' U' L U2 R' U L' U' R",pattern:"BRULFRFBUULBUULUUUFUR"},
  {id:"ZBLL-ASune-16",name:"Anti-Sune 16",group:"Anti-Sune",cp:"3点交換",alg:"B' U' B U' B' U2 B x R' U R' D2 R U' R' D2 x' R2",pattern:"LRUULFFFURBBBULUUUUUR"},
  {id:"ZBLL-ASune-17",name:"Anti-Sune 17",group:"Anti-Sune",cp:"3点交換",alg:"B U2 B' U' B U' B' R' U2 R' D' R U2 R' D R2",pattern:"LFUUBRFRBULRBULUUUFUU"},
  {id:"ZBLL-ASune-18",name:"Anti-Sune 18",group:"Anti-Sune",cp:"対角2点交換",alg:"F U R' U' R F' R' U F' r U R U' r' F R' U2 R U R' U R",pattern:"LLFUBBLRUUFRBUUUUURUF"},
  {id:"ZBLL-ASune-19",name:"Anti-Sune 19",group:"Anti-Sune",cp:"対角2点交換",alg:"U R U2 R' U' R U2 L' U R' U' R' L U L U' R U L'",pattern:"LLUURRFFUBBRBULUUUUUF"},
  {id:"ZBLL-ASune-20",name:"Anti-Sune 20",group:"Anti-Sune",cp:"隣接2点交換",alg:"F U R' U' R F' R' U' R U R' U R F' U' F U' F' U2 F",pattern:"RBUBFFLRUULRUUBUUULUF"},
  {id:"ZBLL-ASune-21",name:"Anti-Sune 21",group:"Anti-Sune",cp:"隣接2点交換",alg:"F U R' U' R F' R' U' R U R' U R2 U2 R' U' R U' R'",pattern:"RBUBRFLLUUFRUUBUUULUF"},
  {id:"ZBLL-ASune-22",name:"Anti-Sune 22",group:"Anti-Sune",cp:"隣接2点交換",alg:"F R' F' r U R U' r' U' R' F' r U R U' r' F",pattern:"RLUBFFLBUURRUUBUUULUF"},
  {id:"ZBLL-ASune-23",name:"Anti-Sune 23",group:"Anti-Sune",cp:"2組交換",alg:"D R' U' R U D' R2 U R' U R U' R U' R U L U' R U L'",pattern:"RBUBFRLLUURFUUBUUUFUL"},
  {id:"ZBLL-ASune-24",name:"Anti-Sune 24",group:"Anti-Sune",cp:"2組交換",alg:"F R U' R' U R U R2 F' R U R U' R2 U L U' R U L'",pattern:"RRUBFRLBUULFUUBUUUFUL"},
  {id:"ZBLL-ASune-25",name:"Anti-Sune 25",group:"Anti-Sune",cp:"2組交換",alg:"L' U R U' L U R' L' U R U' L U R' L U L' U L U2 L'",pattern:"RRUBLRLFUUBFUUBUUUFUL"},
  {id:"ZBLL-ASune-26",name:"Anti-Sune 26",group:"Anti-Sune",cp:"2組交換",alg:"L U' R' U L' U R U R' U R2 U' L' U R' U' L",pattern:"BRUUBRLLFUFLRUBUUUFUU"},
  {id:"ZBLL-ASune-27",name:"Anti-Sune 27",group:"Anti-Sune",cp:"2組交換",alg:"x U2 r' U' r U2 R' F R' F' x' R U L U' R U L'",pattern:"RFUBBRLRUULFUUBUUUFUL"},
  {id:"ZBLL-ASune-28",name:"Anti-Sune 28",group:"Anti-Sune",cp:"2組交換",alg:"D' R U R' U' D R2 U' R U' R' U R' U R U L U' R U L'",pattern:"RLUBFRLRUUBFUUBUUUFUL"},
  {id:"ZBLL-ASune-29",name:"Anti-Sune 29",group:"Anti-Sune",cp:"2組交換",alg:"L' U R U' L U R U R' U R' U' R U' R2 U' D R' U R D'",pattern:"BLUUFRLRFUBLRUBUUUFUU"},
  {id:"ZBLL-ASune-30",name:"Anti-Sune 30",group:"Anti-Sune",cp:"2組交換",alg:"L' U R U' L U R' F R U' R' U R U R2 F' R U R U' R'",pattern:"BLUUBRLFFURLRUBUUUFUU"},
  {id:"ZBLL-ASune-31",name:"Anti-Sune 31",group:"Anti-Sune",cp:"3点交換",alg:"r U R' U' r' F R F' R U2 R' U' R U' R'",pattern:"RRUBBFRLUUFLUUFUUULUB"},
  {id:"ZBLL-ASune-32",name:"Anti-Sune 32",group:"Anti-Sune",cp:"3点交換",alg:"r U R' U' r' F R F2 U' F U' F' U2 F",pattern:"RFUBBFRRUULLUUFUUULUB"},
  {id:"ZBLL-ASune-33",name:"Anti-Sune 33",group:"Anti-Sune",cp:"4点循環",alg:"R U2 R' U' R U' x R' U2 r' U' r U2 R' F R' F' x' R2",pattern:"BBFURRLLUUFLRUUUUUFUB"},
  {id:"ZBLL-ASune-34",name:"Anti-Sune 34",group:"Anti-Sune",cp:"4点循環",alg:"L' U' L U' L' U2 x L U2 r' U' r U2 R' F R' F' x' R2",pattern:"BBUURRFLLUFBRULUUUFUU"},
  {id:"ZBLL-ASune-35",name:"Anti-Sune 35",group:"Anti-Sune",cp:"4点循環",alg:"R' U L U' R U R2 L' U R U R' U' R' U' R' U R'",pattern:"RFUBBRFLUURLUULUUUFUB"},
  {id:"ZBLL-ASune-36",name:"Anti-Sune 36",group:"Anti-Sune",cp:"4点循環",alg:"R' U L U' R U R L' U' R U R U R U' R' U' R2",pattern:"RLUBBRFRUUFLUULUUUFUB"},
  {id:"ZBLL-ASune-37",name:"Anti-Sune 37",group:"Anti-Sune",cp:"3点交換",alg:"B' U' B U' B' U2 B R2 D' R U2 R' D R U2 R",pattern:"BRUULLFFRUBFRULUUUBUU"},
  {id:"ZBLL-ASune-38",name:"Anti-Sune 38",group:"Anti-Sune",cp:"3点交換",alg:"F U2 F' U' F U' F2 r U R' U' r' F R",pattern:"RRUBLLFFUUBRUULUUUBUF"},
  {id:"ZBLL-ASune-39",name:"Anti-Sune 39",group:"Anti-Sune",cp:"3点交換",alg:"R U2 R' U' R U' x R D2 R U R' D2 R U' x' R",pattern:"BRFUBLLLUUFRRUUUUUBUF"},
  {id:"ZBLL-ASune-40",name:"Anti-Sune 40",group:"Anti-Sune",cp:"3点交換",alg:"L' U' L U' L' U2 L F' r U R' U' r' F R",pattern:"RRUBBLFLUUFRUULUUUBUF"},
  {id:"ZBLL-ASune-41",name:"Anti-Sune 41",group:"Anti-Sune",cp:"3点交換",alg:"F' U' F U' F' U2 F x R2 D2 R U R' D2 R U' x' R",pattern:"BFFUBLLRUULRRUUUUUBUF"},
  {id:"ZBLL-ASune-42",name:"Anti-Sune 42",group:"Anti-Sune",cp:"3点交換",alg:"F' U' F U' F' U2 F2 R' F' r U R U' r'",pattern:"RFUUBLLRUFLBFUBUUUUUR"},
  {id:"ZBLL-ASune-43",name:"Anti-Sune 43",group:"Anti-Sune",cp:"4点循環",alg:"L U' R' U L' U' R2 U R' U R U' R' U R U2 R'",pattern:"FBURFBLRUULFUUBUUURUL"},
  {id:"ZBLL-ASune-44",name:"Anti-Sune 44",group:"Anti-Sune",cp:"4点循環",alg:"U2 M U2 M2 U2 M U' M2 U' M2 L' U R U' L U R'",pattern:"RBUURBLLFUFLFUBUUURUU"},
  {id:"ZBLL-ASune-45",name:"Anti-Sune 45",group:"Anti-Sune",cp:"4点循環",alg:"R U' R U R U R U' R' U' R2 L' U R U' L U R'",pattern:"RRUULBLBFUFLFUBUUURUU"},
  {id:"ZBLL-ASune-46",name:"Anti-Sune 46",group:"Anti-Sune",cp:"4点循環",alg:"L' U R U' L U R'",pattern:"RRUUBBLFFULLFUBUUURUU"},
  {id:"ZBLL-ASune-47",name:"Anti-Sune 47",group:"Anti-Sune",cp:"4点循環",alg:"x U2 r' U' r U2 R' F R' F' x' R2 B' U' B U' B' U2 B",pattern:"RFUULRLRUBBFFUBUUUUUL"},
  {id:"ZBLL-ASune-48",name:"Anti-Sune 48",group:"Anti-Sune",cp:"4点循環",alg:"R U R' U R U L' U R' U L U L' U L",pattern:"RFUULBLRFUBLFUBUUURUU"},
  {id:"ZBLL-ASune-49",name:"Anti-Sune 49",group:"Anti-Sune",cp:"4点循環",alg:"B U2 B' U' B U' B' L U2 L' U' L U2 R' U L' U' R",pattern:"FFURLBLRUUBFUUBUUURUL"},
  {id:"ZBLL-ASune-50",name:"Anti-Sune 50",group:"Anti-Sune",cp:"4点循環",alg:"F U2 F' U' R' F U' F' U R",pattern:"RFUUBRLLUBRFFUBUUUUUL"},
  {id:"ZBLL-ASune-51",name:"Anti-Sune 51",group:"Anti-Sune",cp:"4点循環",alg:"B U B' U B U2 B' L U2 L' U' L U' L2 U R U' L U R'",pattern:"RFLUBBBLUURFFUUUUURUL"},
  {id:"ZBLL-ASune-52",name:"Anti-Sune 52",group:"Anti-Sune",cp:"4点循環",alg:"M2 U' M2 U2 M2 U' M2 L' U R U' L U R'",pattern:"RLUUFBLBFURLFUBUUURUU"},
  {id:"ZBLL-ASune-53",name:"Anti-Sune 53",group:"Anti-Sune",cp:"4点循環",alg:"L' U R U' R L U R U R U' R' U' R2",pattern:"RLUUBBLRFUFLFUBUUURUU"},
  {id:"ZBLL-ASune-54",name:"Anti-Sune 54",group:"Anti-Sune",cp:"対角2点交換",alg:"L' U R U' L U R' F R' F' r U R U' r'",pattern:"RRUUBLBFUFLLFURUUUUUB"},
  {id:"ZBLL-ASune-55",name:"Anti-Sune 55",group:"Anti-Sune",cp:"3点交換",alg:"F' U' F U' F' U2 F r U R' U' r' F R F'",pattern:"RFUUBLBRFULLFURUUUBUU"},
  {id:"ZBLL-ASune-56",name:"Anti-Sune 56",group:"Anti-Sune",cp:"2組交換",alg:"B' U' B U' B' U2 B",pattern:"RRUULRFFUBBLFULUUUUUB"},
  {id:"ZBLL-ASune-57",name:"Anti-Sune 57",group:"Anti-Sune",cp:"2組交換",alg:"R2 U R U R' U' R' U' R' U' R' U' R U' R'",pattern:"RRFULBLFUUBLFUUUUURUB"},
  {id:"ZBLL-ASune-58",name:"Anti-Sune 58",group:"Anti-Sune",cp:"2組交換",alg:"B U2 B' U' B U' B'",pattern:"FFURBBFRUULLUULUUURUB"},
  {id:"ZBLL-ASune-59",name:"Anti-Sune 59",group:"Anti-Sune",cp:"2組交換",alg:"L' U' L U' L' U2 R2 L U R U R' U' R' U' R' U R'",pattern:"RFUUBBFRLULBFULUUURUU"},
  {id:"ZBLL-ASune-60",name:"Anti-Sune 60",group:"Anti-Sune",cp:"2組交換",alg:"B' U' B U' B' U2 B M2 U' M2 U2 M2 U' M2",pattern:"RLUURRFBUBFLFULUUUUUB"},
  {id:"ZBLL-ASune-61",name:"Anti-Sune 61",group:"Anti-Sune",cp:"2組交換",alg:"M2 U' M2 U2 M2 U' M2 F' U' F U' F' U2 F",pattern:"RLFURBLBUUFLFUUUUURUB"},
  {id:"ZBLL-ASune-62",name:"Anti-Sune 62",group:"Anti-Sune",cp:"2組交換",alg:"F U2 F' U' F U' F' M2 U' M2 U2 M2 U' M2",pattern:"RLUURBFBLUFBFULUUURUU"},
  {id:"ZBLL-ASune-63",name:"Anti-Sune 63",group:"Anti-Sune",cp:"2組交換",alg:"M2 U' M2 U2 M2 U' M2 B U2 B' U' B U' B'",pattern:"FLURRBFBUUFLUULUUURUB"},
  {id:"ZBLL-ASune-64",name:"Anti-Sune 64",group:"Anti-Sune",cp:"4点循環",alg:"L' U R U' L U R' r U R' U' r' F R F'",pattern:"RRFUBLLFUULBFUUUUUBUR"},
  {id:"ZBLL-ASune-65",name:"Anti-Sune 65",group:"Anti-Sune",cp:"4点循環",alg:"R U2 R' U' R U2 R U R U R U' R' U' R2 U",pattern:"FBLURRBLUUFBLUUUUUFUR"},
  {id:"ZBLL-ASune-66",name:"Anti-Sune 66",group:"Anti-Sune",cp:"3点交換",alg:"R' F' r U R U' r' F2 U2 F' U' F U' F'",pattern:"FRUULBLFRUBFLUBUUURUU"},
  {id:"ZBLL-ASune-67",name:"Anti-Sune 67",group:"Anti-Sune",cp:"3点交換",alg:"R' U2 R' D' R U2 R' D R2 B U2 B' U' B U' B'",pattern:"LFUFBBLRUULRUUBUUURUF"},
  {id:"ZBLL-ASune-68",name:"Anti-Sune 68",group:"Anti-Sune",cp:"3点交換",alg:"F U R' U' R F' R' U2 L U' R U L'",pattern:"FFUURFBLURBLLURUUUUUB"},
  {id:"ZBLL-ASune-69",name:"Anti-Sune 69",group:"Anti-Sune",cp:"隣接2点交換",alg:"R2 D' R U2 R' D R U R U' R' U2 R U'",pattern:"LLUFBLBRUUFRUURUUUBUF"},
  {id:"ZBLL-ASune-70",name:"Anti-Sune 70",group:"Anti-Sune",cp:"4点循環",alg:"F U2 F' U' F U' F' U R2 D' R U2 R' D R U2 R",pattern:"FFRUBBFLUURLLUUUUURUB"},
  {id:"ZBLL-ASune-71",name:"Anti-Sune 71",group:"Anti-Sune",cp:"4点循環",alg:"F U R' U' R F' U' R' U2 R",pattern:"FFUUBRRLUBRLLUFUUUUUB"},
  {id:"ZBLL-ASune-72",name:"Anti-Sune 72",group:"Anti-Sune",cp:"2組交換",alg:"R' U2 R' D' R U2 R' D R2 F R' F' r U R U' r'",pattern:"FBRULLFRUUFBLUUUUUBUR"}
];
